### ISSUE TITLE
Update Power BI Desktop on VM to a Microsoft-supported build

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#1]
Refer to https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/issues/153 for the details. This issue was unresolved in DA-100 and got carried over into PL-300. The build on the ALH VMs is still the unsupported August 2021 release.

**Comment by markfitzqa** [comment]
Vitaly, that is not going to happen any time soon.  All screenshots would need to be replaced as well.

**Comment by markfitzqa** [comment]
Update: both LearnOnDemand and GoDeploy have Power BI Desktop (Feb 2022) edition installed, but now the instructions in GitHub do not match.  The github instructions do not match.

**Comment by VitalyMCT** [comment]
GoDeploy had the August 2021 release just a few days ago. I suppose they decided to upgrade (?)

Skillable / LODS had the February 2022 release as of yesterday, and a whole bunch of custom-added overrides to try to patch up the instructions to that release. I opened a ticket with them to try to get to the bottom of the issues.

It's a really messy situation. There needs to be a standardized PBI Desktop version provided on the VM that goes to the ALHs (current version, in line with Microsoft's own supportability policies at the link in this issue). And then the instructions need to map to that version.

**Comment by bpmoring** [comment]
Thanks @VitalyMCT and @markfitzqa, we are looking into this issue and will update here accordingly.

**Comment by VitalyMCT** [comment]
@bpmoring Since this is breaking the lab experience, can you please provide a timeline on the fix?

**Comment by bpmoring** [comment]
Hi @VitalyMCT  what lab experiences are being broken? Is it just GoDeploy?

**Comment by VitalyMCT** [comment]
@bpmoring I am not sure what additional information you are requesting, as the issue is already described in great detail in this thread. 

The official lab instructions in this repo are out of sync with the VM images ALHs apparently received. That's the problem, in a nutshell. It needs to be fixed by Microsoft, in the official repo. Not left to any of the ALHs to patch in their own ways. The MCTs do not have control over how GoDeploy or any other ALH attempts to patch around the issue in the official repo.

Can the MCTs here please get some details on the resolution plan & time frames?

**Comment by bpmoring** [comment]
Hi @VitalyMCT the plan is to confirm GoDeploy is updated to the February 22 version of Power BI. We will also be updating all imagery in the instructions this coming Friday, 3/25.

**Comment by VitalyMCT** [comment]
@bpmoring 

Regarding

> We will also be updating all imagery in the instructions this coming Friday, 3/25

To emphasize, the regressions here around more than just images. When jumping 6 releases of a fast-moving platform like Power BI there are going to be functional adjustments needed as well. Are there being done, via a complete retesting of the lab instruction steps?

As far as timing, it's a little problematic, as many of us, myself included, are running PL-300 classes starting next Monday. If the corrections are delayed another week it would give ALHs no time to adequately incorporate and test them and MCTs no time to verify the results. 

This issue was created a long time ago, when the decision was apparently made to push PBI Desktop February 2022 to the official PL-300 VM images without syncing instructions accordingly. Can the fixes be expedited to match their urgency?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review That's a strange comment. What does it mean in the context of this issue?

**Comment by bpmoring** [comment]
All images and instructions have been updated to the latest VM version.
