### ISSUE TITLE
Date column from examples

### ISSUE THREAD

**Issue by pahe81** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#100]
# Module: 3
#### Step: 14

Description of issue
"In the Column1 column, in the first grid cell, commence entering 7/1/2017, and then press Enter."
Power Query does not pick up on the dates without the leading zeros in the example (MonthNumber column has leading zeros) . Need to enter "07/01/2017" for the column to produce dates.

**Comment by bpmoring** [comment]
Thank you for mentioning this. We will take a look.

**Comment by AngieRudduck** [comment]
This will go live in November 2022 updates.
