### ISSUE TITLE
Add the following fields to the visual wells/areas:

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#101]
# Module: Design a Report in Power BI Desktop, Part 1
#### Step: 33

Description of issue
Add the following fields to the visual wells/areas:

Repro steps: 33

1.Add the following fields to the visual wells/areas:

Axis: Product | Category it should be x-Axis

Value: Sales | Quantity ( it should y Axis)

1.
1.

**Comment by AngieRudduck** [comment]
Duplicate issue, already included in November 2022 updates.
