### ISSUE TITLE
Multi-Row Card formatting, old instructions

### ISSUE THREAD

**Issue by pahe81** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#102]
# Module: 7
#### Step: 7

Description of issue
Instructions based on old formatting pane
"In the Data Labels group, increase the Text Size property to 28pt" > Should be Callout value group
"In the Background group, set the Color to a light gray color"  > Could give the path to the Background group (General tab > Effects)

**Comment by AngieRudduck** [comment]
Fix included in November 2022 updates.
