### ISSUE TITLE
Instructions in "Design a Report in Power BI Desktop, Part 1" incorrect?

### ISSUE THREAD

**Issue by digitalIceCream** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#103]
# Module: 07
#### Step: 04 (Task 1) / 03 (Task 2)

Description of issue
Task 1 - Step 4:

It is not clear where those details are supposed to come from and it is not clear what filepath **Resources** (IF a file?) is referring to. I have not received any account details. Not from the download in the lab itself and not anything via email.

---

Task 2 - Step 3:

When I log in with my Uni account (for example) I do not have those options available to me. Also, the web interface looks slightly different now?

Repro steps: ???

1.
1.
1.

**Comment by AngieRudduck** [comment]
The Microsoft Learn Exercise page has been updated to include instructions for account details. You must use an organizational account. If using your uni account, you may have restricted access from the organization. You can create a free M365 developer account for full experience, but this is not required.
