### ISSUE TITLE
Button text property incorrect setting

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#104]
# Module: Create reports, part 2
#### Step: 3 (Select the button, and then in the Format button pane, click General and turn the Title property to On.)

Description of issue

The title property to be configured is a different one.

**Incorrect statement**: Select the button, and then in the Format button pane, click General and turn the Title property to On.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/53346841/196649929-a7676169-5c1b-4dd2-9efa-2af08e14c0dc.png">

**Correct statement**: Select the button, and then in the Format button pane, expand the Style section and turn the Text property to On. In the Text box, enter Bar Chart.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/53346841/196650075-ecaaccb4-c95f-4957-9e09-eaede3f5080a.png">

**Comment by AngieRudduck** [comment]
Thank you for the detailed report. This will be updated in the November 2022 release.
