### ISSUE TITLE
Lessons duplicated

### ISSUE THREAD

**Issue by Alexdc-12** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#108]
# Module: PL-300
## Lab/Demo: 8&9

Description of issue
Lessons 8 & 9 are duplicated in the labs folder. Whilst following this module lesson 8 & 9 are also in the wrong order, lesson 8 is called perform-data-analysis-in-power-bi-desktop/Solution but if references using the solution from lesson 8 which is called create-power-bi-dashboard

I believe the correct order is 08 - Create a a Power BI Dashboard and then 09 - Perform data analysis in power BI Desktop/Solution

It looks like these duplicate folders were introduced as part of a bugfix in commit [522f000]

Repro steps:

start on lab 8 and start to notice the inconsistencies in instructions, then reference the labs files and see duplicate folders for lesson 8 & 9.
![Screenshot 2022-11-17 102132](https://user-images.githubusercontent.com/48382348/202420988-b5c93c8c-8489-45d2-be14-5ae827b74d2d.png)

**Comment by VitalyMCT** [comment]
@Alexdc-12 I am a fellow MCT who's preparing for my next session of the course by reviewing the outstanding issues.

It seems that the duplication has been fixed. Can you please confirm?

**Comment by AngieRudduck** [comment]
@Alexdc-12  and @VitalyMCT - duplication was temporary to prevent broken labs, and you're very thorough and caught it before I was done.
