### ISSUE TITLE
Lab 2 Ex 1 Task 6 - Missing Step or Incorrect Screenshot

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#109]
# Module: 3
#### Step 5: In the status bar, verify that the query has four columns and 10 rows.

Description of issue
There are 11 rows in the Region query. There should be (or once was) a step to filter Corporate HQ from the Group column. That step is gone. Step 5 indicates that there should be four columns and 10 rows but since that row is not filtered out, there are four columns and 11 rows. 

Proposed fix
Add a step to exclude Corporate HQ from the Group column. The solution file for Lab 2 is correct - a step to Keep Rows where SalesTerritoryAlternateKey does not equal 0 Is in present in PQ, which makes the number of rows 10, as per the screenshot.

Workaround
Have students filter to exclude Corporate HQ from the Group column to make the number of rows 10, as per the screenshot.

**Comment by Jason-M-Richards** [comment]
Thanks @jamarx2 , echoeing the issue

**Comment by AngieRudduck** [comment]
Thank you for this catch. We will apply bug fixes by end of next week.

**Comment by AngieRudduck** [comment]
This has been updated in the latest PR.
