### ISSUE TITLE
Model Data in Power BI Desktop, Part 1

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#11]
"Part 1" should be removed from the lab name, as there is no Part 2. It seems to be a copy & paste issue from DA-100, which did have 2 lab parts.

**Comment by bpmoring** [comment]
Thank you, we will update this on Friday.

**Comment by bpmoring** [comment]
Update has been made.
