### ISSUE TITLE
Creating column from examples causes an extra 0 to the date format

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#110]
# Module: 02
#### Step: 14 : In the Column1 column, in the first grid cell, commence entering 07/01/2017, and then press Enter.

Description of issue : 
When they write down 07, it adds an extra 0 prefix to the rest of the numbers even if they were 2 digits. Example: 11/11/2017 would be created in the new column as : 011/11/2017. This causes an error to the date type conversion at later step. They should enter the example as : 7/01/2017.

Repro steps:

1. Step: 14 : In the Column1 column, in the first grid cell, commence entering 7/01/2017, and then press Enter.
1.
1.

**Comment by jamarx2** [comment]
I ran into this as well.

**Comment by AngieRudduck** [comment]
Thank you for this catch. We will apply bug fixes by end of next week.

**Comment by AngieRudduck** [comment]
Updates have been made. There is also a note about the VM setting, in case it's not in US.

![image](https://user-images.githubusercontent.com/34583336/210394072-d1a5a591-b378-445f-95f4-75c9018dde8c.png)
