### ISSUE TITLE
Create DAX Calculations in Power BI Desktop, Part 2 Step Missing

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#112]
# Module: 05 Part 2
#### Step: 01

Description of issue
The last step in the prior task has us in Model View.   For the steps in Task 3 for clean up, we need to add a step for us to switch to Report View as a new Step 1.

Repro steps:

1.
1.
1.
![Item 2](https://user-images.githubusercontent.com/16696370/205124721-e93119ca-fb12-4102-8984-5cc1c89ddf2e.png)
![Item1](https://user-images.githubusercontent.com/16696370/205124725-12fe486d-96a2-4cd1-9e09-011c0ac10fcc.png)

**Comment by AngieRudduck** [comment]
Hi Jeff, thank you for the feedback, it's much appreciated. I will add an item for the backlog to add a step to clarify to move back to the report view. Please note, our labs are not designed to be a complete step-by-step instruction and there is a certain level of effort required by learners. There are previous steps that explain how to create new pages on Report View, so being able to delete pages from that view should be retained. If a learner struggles with finding this, the instructor is there to help guide them.
