### ISSUE TITLE
Module 7 Design a Report in Power BI Desktop, Part 1 Edge Graphic Needs Updating

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#113]
# Module: 07
#### Step: 01 and Step 2

Description of issue

Step 1: Should say to open Power BI Desktop.

Step 2: The Settings graphic is different now in EDGE. Update graphic
.
![Item 3](https://user-images.githubusercontent.com/16696370/205178266-323afd57-ce36-4252-a25b-a70296bc142e.png)

**Comment by AngieRudduck** [comment]
Thank you for submitting this bug. This screenshot will be removed entirely in the next update by end of next week.
