### ISSUE TITLE
Module 7: Design a Report in Power BI Desktop, Part 1

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#114]
# Module: 07
#### Step: 08

Description of issue
Step 8: Format the visual:
In the Callout values group, increase the Text Size property to 28pt
**In the Background group, set the Color to a light gray color**

The directions for the background color needs to be updated.  It is now under the Cards group, and there is no color called gray. Maybe state it should be "White, 20% Darker".

If I am missing where this original instructions setting is let me know .

Jeff Smalley MCT
Chicagoville

![Item 1](https://user-images.githubusercontent.com/16696370/205460359-2d4afd79-c388-4ef4-9a64-a1046f3004c6.png)
![Item 2](https://user-images.githubusercontent.com/16696370/205460360-8a32af4d-6e0b-4dbc-b0d3-0dabb2fed876.png)

**Comment by AngieRudduck** [comment]
Please note the updated instructions now say:

**In the General > Effects > Background group, set the Color to a light gray color (such as “White, 20% Darker) to give contrast**

![image](https://user-images.githubusercontent.com/34583336/210394409-ddaceee6-ebb8-4e42-9092-0606909d2690.png)
