### ISSUE TITLE
Module 7: Design a Report in Power BI Desktop, Part 1

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#115]
# Module: 07
#### Step: 10

Description of issue
Instructions need to be updated...

Currently it states:
Step 10: Add the following fields to the visual wells/areas:

Axis: Date | Month

Value: Sales | Sales and Targets | Target

It should be corrected to:

Y-Axis: Date | Month

X-Axis: Sales | Sales and Targets | Target

Cheers,
Jeff Smalley MCT
Little Chicago

![Item 3](https://user-images.githubusercontent.com/16696370/205461472-e68abb0f-17d0-4b67-8e55-670b3e283de3.png)

**Comment by VitalyMCT** [comment]
This one seems to be related to https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/issues/96.

It would be beneficial to check other steps / visualizations for the same UI renaming while resolving this issue.

**Comment by AngieRudduck** [comment]
This has been updated.

![image](https://user-images.githubusercontent.com/34583336/210394777-113a2746-923b-48b1-85fc-2260a6efc184.png)
