### ISSUE TITLE
Dashboard lab: old file paths

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#116]
There are references in this lab to file paths that no longer exist. Example:

> In the Open window, navigate to the D:\PL300\Labs\**08**-create-power-bi-dashboard\Starter folder.

This issue was introduced when the lab numbers were updated. Please fix this and check other labs for similar issues.

**Comment by AngieRudduck** [comment]
File paths have been updated.

![image](https://user-images.githubusercontent.com/34583336/210395005-c3169a68-dca4-4af3-abc6-b42666c83048.png)
