### ISSUE TITLE
Discrepancy between lab and folder names

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#117]
For "Analyze data with AI visuals" lab (new title) the folder is still called "08-perform-data-analysis-in-power-bi-desktop". This is very confusing to the students. Please align the naming for this lab and any other labs that might've been impacted.

**Comment by VitalyMCT** [comment]
A related issue here is that the new lab name is, IMO, a bit problematic. The lab consists of asking attendees to use the scatter chart visual and the forecasting feature in the line chart visual.

- The former is just an advanced built-in visual. There is no AI involved at all, especially in the simple configuration used in the lab (no clustering, etc.).
- The latter's relevance to AI can perhaps be debated as linear regression can be sometimes deemed to be a form of ML. For example, see https://stats.stackexchange.com/questions/268755/when-should-linear-regression-be-called-machine-learning. I personally think it's a bit of a stretch, at least in so far as AI is commonly perceived today and in relation to more advanced AI capabilities in Power BI.

I think calling this lab "Analyzing data using advanced visualizations", or something along these lines, would be more inclusive and more accurate.

**Comment by AngieRudduck** [comment]
Thank you for this feedback. There is the Microsoft Learn module, the lab, the lab folder structure, and the ILT PowerPoint slides that all need to be aligned for consistency. With that in mind, these changes may not all be updated in this December bug fix release.

**Comment by AngieRudduck** [comment]
Please note that the lab instructions title has been updated. Other changes will still be made later.

**Comment by AngieRudduck** [comment]
This will be updated in the next course update, scheduled for Friday January 13th.
