### ISSUE TITLE
Load Data in Power BI Desktop - Step sequencing issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#118]
See screenshot below

![image](https://user-images.githubusercontent.com/1765732/205957953-d9aa6150-ed2a-4937-920a-bc201ee8d1e6.png)

**Comment by AngieRudduck** [comment]
@VitalyMCT  please provide more explanation of what you expect to see and what is wrong with this as is.

**Comment by VitalyMCT** [comment]
The highlighted block belongs to step 7 rather than after step number 8.

**Comment by AngieRudduck** [comment]
This has been updated. I see there's a formatting issue with the snippet text that will be corrected as soon as possible. 

![image](https://user-images.githubusercontent.com/34583336/210410744-d91759fa-0fa9-44fc-8525-f35c8ce47cbf.png)

**Comment by VitalyMCT** [comment]
@AngieRudduck Thanks for the update. Since as you noted there is still a (new) issue with the Markdown I recommend either keeping this item open or opening a new issue. This is in keeping with standard GitHub conventions.
