### ISSUE TITLE
Wrong instruction after module order change

### ISSUE THREAD

**Issue by GildardoRojas** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#119]
# Module: 08
#### Step: 04 Open previous solution PBIX file

Description of issue
The instruction asks to navigate to D:\PL300\Labs\08-create-power-bi-dashboard\Solution
it should ask to navigate to D:\PL300\Labs\07-design-report-in-power-bi-desktop-enhanced\Solution to load 'Sales Analysis.pbix' 

Repro steps:
Executing this step as it is now leads to an error as the only file there is Sales Exploration.pbix not Sales Analyisis.pbx, learners usually try to load Sales Exploration and that file doesn't have a data set.

**Comment by AngieRudduck** [comment]
Thank you for this feedback. The current instructions seem out of place with other labs considering you need to go to a previous lab's solution. We will create a new "starter" folder in this specific lab, with the appropriate folder, and the flow will be more consistent. Update should come by end of next week.

**Comment by AngieRudduck** [comment]
This has been updated. If you have issues, please let us know.
