### ISSUE TITLE
Some (possibly all?) lab files still refer to D:\DA100\ path for data files

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#12]
# Module: 1
## Lab/Demo: 1

Refreshing the data in the lab 1 solution file returns an error, because it is looking for D:\DA100, which of course has been replaced by D:\PL300. I assume this is probably true for many, if not all, of the other files.

![2022-03-14_12-24-38](https://user-images.githubusercontent.com/7502186/158216911-ab2a7970-aab3-4067-a63d-01e710bf4146.png)

**Comment by bpmoring** [comment]
Thank you, we will look into this issue.

**Comment by gethynellis** [comment]
I know you are looking at this but I found this today too

**Comment by bpmoring** [comment]
This issue has been resolved.

**Comment by dancostello70** [comment]
Thank you!!

**Comment by dancostello70** [comment]
Sorry, but the issue seems not to be resolved...

![image](https://user-images.githubusercontent.com/7502186/162510846-247dd5f5-50eb-4042-a607-5dd5d50b8590.png)

I just cloned the repo, refreshed the data, and got the exact same error.

**Comment by bpmoring** [comment]
I am updating the labs in VS and will be pushing all of the updates out later today.

**Comment by dancostello70** [comment]
Oh great -- I have a colleague who is teaching it next week and will be very happy to hear that!
