### ISSUE TITLE
Analyze data with AI visuals => Task 2: Get started – Create a dataset => New UX

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#120]
The steps in this task would need to change within the next few weeks. See "_Upcoming changes to the ‘Get Data’ experience in the Power BI Service_" at https://powerbi.microsoft.com/en-us/blog/power-bi-december-2022-feature-summary for details.

If there is no way for end-users to control the associated rollout schedule (ex. optional toggle for new UX) the instructions may need to cover both the new and old ways simultaneously while the new way is rolling out.

**Comment by AngieRudduck** [comment]
This is now updated.
