### ISSUE TITLE
New Power BI Service Navigation UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#121]
The new UI has rolled out more widely and now applies to most if not all ALH accounts. 

This impacts instructions in Design a Report in Power BI Desktop, Part 1 lab, Exercise 2, Task 1. There are likely other impacts as well that should be reviewed and adjusted as appropriate.

New UI:

![image](https://user-images.githubusercontent.com/1765732/207622213-33e7a348-a463-453c-bdfd-f8009fdd9979.png)

**Comment by AngieRudduck** [comment]
Thanks for the feedback. Is the navigation concern about where My Workspace is located in the expanded blade? The navigation still provides accurate details to get to My Workspace. 

![image](https://user-images.githubusercontent.com/34583336/207771470-28d31c91-6269-4e97-be6d-35f046743d10.png)

**Comment by VitalyMCT** [comment]
It's more than that. 

Starting with this step the instructions do not align to the new UI (ex. there is no "expand My Workspace" capability anymore). A bunch of screenshots are no longer applicable as well. 

Once you run through this and other labs on the new Power BI UI you will see all the impacts and be able to adjust them.

**Comment by AngieRudduck** [comment]
Updates have been made in the appropriate labs.
