### ISSUE TITLE
Design a Report in Power BI Desktop, Part 1 - Filtering UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#122]
The UI around the filter icon has changed. 

This impacts Exercise 2, Task 1, Step 9. There may be other impacts as well (in this and other labs) that should be reviewed and adjusted accordingly.

New UI:

![image](https://user-images.githubusercontent.com/1765732/207623924-16fccdcf-0edc-43ae-b182-3760b0b0b221.png)

**Comment by AngieRudduck** [comment]
Flagged for January updates.
