### ISSUE TITLE
Design a Report in Power BI Desktop, Part 1 => Location of Map Settings in Power BI Desktop

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#123]
Exercise 1, Task 2, Step 1:

> In Power BI Desktop, navigate to Options > Options and Settings > Global and check the box for Use Map and Filled Map visuals.

The location is a bit different:

1) The beginning of the breadcrumb should include File
2) The end of the breadcrumb should include Security tab

Please update instructions accordingly.

**Comment by AngieRudduck** [comment]
Maps have been removed from the lab, and therfore this is resolved.
