### ISSUE TITLE
Analyze data with AI visuals => Exercise 1 => Task 3 => Step 9 => Different UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#124]
The UI around connecting to Power BI datasets is different from the instructions in the version of Power BI Desktop deployed to ALH machines (July 2022). Please update instructions accordingly.

Actual UI:

![image](https://user-images.githubusercontent.com/1765732/207672686-cd25a184-8f8e-4cb4-8217-5b4ee5a302c1.png)

**Comment by AngieRudduck** [comment]
Please confirm you're referencing the correct lab/exercise/task. Lab 8 - Perform Data Analysis in Power BI Desktop > Exercise 3 is about adding a Forecast. 

https://microsoftlearning.github.io/PL-300-Microsoft-Power-BI-Data-Analyst/Instructions/08-perform-data-analysis-in-power-bi-desktop.html#exercise-3-create-a-forecast

As mentioned in #125, we are in process of updating the Power BI Desktop version, so if this is for a different issue, we will be updating screenshots as well.

**Comment by VitalyMCT** [comment]
Sorry, fixed the reference now. Hard to get all these items filed when simultaneously running a live classroom.

**Comment by AngieRudduck** [comment]
Power BI Desktop version update pending on ALH deployment. Will close once complete.

**Comment by VitalyMCT** [comment]
@AngieRudduck Thanks for the update. 

Which PBI Desktop version will be pushed out and approximately when? 

I am teaching PL-300 again shortly and need to prepare with the same PBI Desktop version the attendees will be using in ALH environment. Other MCTs are in the same boat.

**Comment by AngieRudduck** [comment]
The VM updates have been pushed, and the ALHs have their own SLAs. It should be updated within the next 2 weeks depending on ALH.
