### ISSUE TITLE
Upgrade Power BI Desktop on ALH VMs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#125]
- Current version on ALH VM image: July 2022
- Microsoft-supported version: December 2022 (https://powerbi.microsoft.com/en-us/blog/power-bi-december-2022-feature-summary/)

Please refer to https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/issues/1 for details around the importance of staying on Microsoft-supported versions.

**Comment by AngieRudduck** [comment]
1. Thanks for the feedback. We are currently in the process of updating the version. Updates are on a different schedule for VMs so we will communicate update schedule when we have a date.

**Comment by AngieRudduck** [comment]
The VM updates have been pushed, and the ALHs have their own SLAs. It should be updated within the next 2 weeks depending on ALH.

**Comment by VitalyMCT** [comment]
@AngieRudduck Thanks for the update. 

Which PBI Desktop version have the current instructions been designed & QA'd on? July 2022? December 2022? Or something else?

And how can MCTs know which version is in flight to ALHs? Is it December 2022? Or something else?

**Comment by AngieRudduck** [comment]
December 2022 is being released.

**Comment by VitalyMCT** [comment]
Ok, perfect. Can you please also address these items:

> Which PBI Desktop version have the current instructions been designed & QA'd on? July 2022? December 2022? Or something else?

**Comment by AngieRudduck** [comment]
The instructions have been released to align with December 2022 Power BI Desktop version and the current version of Power BI service (as of December 2022 as well).

**Comment by VitalyMCT** [comment]
@AngieRudduck For MCTs' benefit, can you please provide some additional details around how that VM update is supposed to flow to AHLs? I've contacted a few and see some confusion and inconsistency around the release process.

Is this new VM released by Microsoft to its ALHs as:

1) New VM image. That's my understanding based on the explanation above. Is Microsoft providing a new VM image to its ALHs and asking them to use it for this Microsoft Official Curriculum course?
2) Instructions to patch old VMs with new software. Some ALHs have taken this approach. Is this an official, Microsoft-directed and supported process? If so, how does Microsoft instruct ALHs towards a consistent set of software + settings to use within the VMs they patch up (i.e. config that matches and is fully QA'd against the official Microsoft instructions)?
3) Something else? If so, what?

Current ALH status tracker for this VM deployment is below. Please feel free to update with additional ALHs.

1) Skillable: new VM deployed for both MOC and ESI lab versions
2) GoDeploy: yet to receive new VM from Microsoft. Patched old VM with Dec 2022 PBI Desktop release.

**Comment by AngieRudduck** [comment]
@VitalyMCT The update was released to current ESI/MOC/Microsoft Learn ALH (Skillable). Please contact the other ALHs directly for timing on how long they will take to update the image.

As the content developer, it's my job to ensure that the correct version of the Power BI Desktop software is updated when required and lab instructions are accurate. I cannot speak to how the ALHs choose to update the VM whether updating their existing image or pushing a new image. Please contact them regarding their operational processes.

**Comment by VitalyMCT** [comment]
@AngieRudduck So Microsoft releases the update to Skillable only (as a VM)? How does Microsoft flow it to other ALHs?

**Comment by AngieRudduck** [comment]
Normally the VMs are made available to all ALHs prior to a course update being published.  The team is looking into what happened this time around and will work to ensure this process is followed moving forward.

**Comment by VitalyMCT** [comment]
@AngieRudduck This is incredibly confusing. It seems from the above that there has been a process error that resulted in a delay in releasing an updated Microsoft-standardized course environment to ALHs. Is that the case? 

Most importantly, _as of today_, has the updated VM containing such an environment been distributed to (all) ALHs? Or is that still in flight too? If it's in flight, what's the ETA?

We have ALHs telling MCTs they received no updated VMs from Microsoft, so they are trying to improvise, which causes configuration drift, environments that are inconsistent with Microsoft's own parameters (which are presumably in the standardized VM), etc.

**Comment by AngieRudduck** [comment]
@VitalyMCT I understand the confusion and frustration with this recent release, however I won't be able to provide the level of detail you're requesting. 

I appreciate this is not an ideal situation for you as you try to prepare for future deliveries, and **there are no breaking changes that should prevent you from delivering the course**. The only difference is the Power BI Desktop version. In the new VM, we have December 2022 and the lab instructions reference December 2022 changes for certain items like slicer formatting, but that can be covered in class if the VM is the older version.

If you are working with an ALH that has the previous version, you could acknowledge to your students that this is an evolving product. In the real world, they may not have access to the same product version we use and may have to adjust.
