### ISSUE TITLE
Lab Instruction Step

### ISSUE THREAD

**Issue by pnk1119** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#127]
# Module: 08
#### Step: 04

Description of issue:
In Step 4 , it is mentioned to navigate to a folder as below. However , with the lab swap ( Lab 8 and 9 ) , this , path needs to be updated.
Current  : In the Open window, navigate to the D:\PL300\Labs\08-create-power-bi-dashboard\Solution folder
Suggested : In the Open window, navigate to the D:\PL300\Labs\09-create-power-bi-dashboard\Solution folder.

Repro steps:

1.
1.
1.

**Comment by AngieRudduck** [comment]
This has been updated.
