### ISSUE TITLE
Remove list of 10 labs from the lab story

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#130]
Description of issue. The list of labs that is displayed as part of the lab story in every exercise (10 labs, with the checkboxes) is confusing for learners. They think they need to "load data" somewhere, they think they need to do certain activity and check the box. Might be better to just remove this. Or remove the checkboxes from this part.

![image](https://user-images.githubusercontent.com/53346841/208427620-f3629651-f6e2-4e33-a683-87d5feb35f9d.png)

**Comment by AngieRudduck** [comment]
This is good feedback, and we'll keep it in mind, however these lab instructions are used for Microsoft Learn labs as well.
