### ISSUE TITLE
Lab 2: Load Data in Power BI Desktop

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#132]
# Module: 03
#### Step: 5

Description of issue
Step requests student to "verify that the query has four columns and 10 rows." 
Current data set includes 11 rows, including the "Corporate HQ" row
Repro steps:

1.
1.
1.

**Comment by AngieRudduck** [comment]
Duplicate issue. Was fixed in the December updates.
