### ISSUE TITLE
PowerBI Service UI update

### ISSUE THREAD

**Issue by elenamoor** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#133]
# Module: 00
#### Step: task 2. 1-6 and Task 3 steps 9-11

Description of issue: the UI has changed and there is no option Get Data on the service side. Instead it has to be New -> Dataset etc.

Then in task 3 for powerBi datasets instead of Create this button is "Connect"

**Comment by AngieRudduck** [comment]
Duplicate
