### ISSUE TITLE
Review mismatch/ step may be missing

### ISSUE THREAD

**Issue by Yash-malhi** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#134]
![PL 300 err](https://user-images.githubusercontent.com/88126448/209906752-4635d4a9-97ce-4633-8997-775ba8d2ed71.png)
# Module: 03
#### Step: 05

Description of issue:
Profiling steps indicate that there should be 10 rows however it includes the HQ row making it 11. There is no step mentioning it and on multiple occassions causes confusion for a lot of people.

Repro steps:

1.
1.
1.

**Comment by AngieRudduck** [comment]
This is duplicate.
