### ISSUE TITLE
Remove lab "part #'s" from lab names in 4 labs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#136]
See screenshot below from https://microsoftlearning.github.io/PL-300-Microsoft-Power-BI-Data-Analyst

Background: Lab part numbers were applicable to old version of lab instructions, to distinguish labs that used to have the same names. This no longer applies to the new labs, because all lab names are now unique, thus making the part references confusing.

![image](https://user-images.githubusercontent.com/1765732/210412607-47c9aa94-c6c4-4e1e-8ebd-39584c9be004.png)

**Comment by AngieRudduck** [comment]
Thank you for your opinion. We will consider this in future updates, but are not planning to change this now.

**Comment by VitalyMCT** [comment]
@AngieRudduck 

Sorry, this is more than an opinion, it's a constructively justified request to make a correction. It only makes sense to call items "parts" if they represent one whole. Either the lab names are the same (that was the situation in an old version, when the "part" suffix was initially added), or the lab names are different and they are just separate labs (functionally, that's the situation now).

If a detailed request for a correction is denied let's please add a constructive explanation with the reason and please explain that reason in terms of how it helps customer success with the labs, i.e. benefit to attendees in live PL-300 classrooms.

Also, let's please try to follow standard GitHub issue handling convention and only close resolved issues. 

The "_we will consider this in future updates_" is a wonderful comment after which the issue should remain open until something is done. Otherwise issues are going to be lost in a pile of closed issues (lots of examples in this repo + in DA-100 predecessor) and other stakeholders, many MCTs included, cannot easily tell what resolved and what's not, duplicate issues get opened, etc.
