### ISSUE TITLE
Lab timing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#137]
Currently all labs are specified at 45 minutes, even though they have vastly varying actual duration. For example, lab 10 rarely takes attendees more than 15-20 minutes to complete, while lab 2 often takes around an hour. 

I thus suggest adjusting estimated duration in each lab to reflect the lab length. A rough estimate can be done based on lab Markdown complexity, with estimates refined further based on beta teaches and real-world feedback from MCTs.

**Comment by AngieRudduck** [comment]
I appreciate your opinion on this subject. Not every person is able to complete the labs in the same amount of time. The labs will continue to evolve, which may affect the timing, and it will be updated at that time. For now, the labs have no new steps so they won't be longer, and it's extra time for those who finish early.

**Comment by VitalyMCT** [comment]
@AngieRudduck Sorry, the items you rephrased do not represent the suggestion being made by me. The suggestion is to adjust estimated duration to reflect lab complexity, not to somehow try to capture per-student variation.

If one lab is 1/3 or even 1/4 the complexity of another (even by the simplest line-of-instructions metric) it should not have the same recommended duration. That just does not make sense from an attendee experience perspective.

**Comment by AngieRudduck** [comment]
@VitalyMCT I appreciate the clarification. I understand your intent and appreciate the feedback. With the continued updates of the labs, I will review the timing based on edits.

**Comment by AngieRudduck** [comment]
@VitalyMCT  I appreciate the clarification. I understand your intent and appreciate the feedback. With the continued updates of the labs, I will review the timing based on edits in a future course update.

**Comment by AngieRudduck** [comment]
Copying this to Courseware backlog and closing in GitHub.
