### ISSUE TITLE
Lab 1, Exercise 1, Task 2 - Incorrect step numbering

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#138]
See screenshot below. 

Please review the rest of this lab and other labs for similar numbering issues to ensure numbering is sequential. This is very important because in the classroom we use step numbers to help attendees troubleshoot labs.

![image](https://user-images.githubusercontent.com/1765732/210414659-4377f897-641f-4b34-a404-118726e2ad33.png)

**Comment by AngieRudduck** [comment]
Confirmed formatting issue. Will fix in next PR.
