### ISSUE TITLE
Update names of first 2 labs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#139]
Please consider updating the names to match the lab contents. 

For example, simply swapping the names would seem to be appropriate. Rationale:

- First lab covers data loading + data preview/profiling. Calling it "load data..." would make sense.
- Second lab focuses on Power Query (aka Power BI's data prep technology) and associated transformations. Calling it "prepare data..." would make sense.

Currently the names are reversed, which is really confusing.

**Comment by AngieRudduck** [comment]
I've copied this to the Courseware backlog for review on the next content update. Thank you for your feedback.
