### ISSUE TITLE
"Create DAX Calculations in Power BI Desktop, Part 1" lab - Markdown issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#141]
Block is marked as code in Markdown, whereas it should be just a normal list. Reference https://microsoftlearning.github.io/PL-300-Microsoft-Power-BI-Data-Analyst/Instructions/04-create-dax-calculations-in-power-bi-desktop.html

![image](https://user-images.githubusercontent.com/1765732/211163599-023dada1-2cb3-4b7f-bf1d-2946af6c63ad.png)

**Comment by AngieRudduck** [comment]
Fixed.
