### ISSUE TITLE
PPT Slides

### ISSUE THREAD

**Issue by bhmand** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#142]
# Module: All
#### Step: All

Description of issue

Why is PPT slides, demos etc. not updated ? There is no way I can deliver this course when you only update labs :(

**Comment by AngieRudduck** [comment]
@bhmand Thank you for the feedback. Labs were updated first because the priority was assessed higher. Slides will be updated soon as well. GitHub is for issues specific to labs. If you have issues with the slides, please use the MCT Courseware Forum. Regards.
