### ISSUE TITLE
PL-300 02-load-data-with-power-query-in-power-bi-desktop.md Lab Steps

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#144]
#### **Priority**
Low Priority - Small Lab step Changes

#### **Lab/Demo Number/Name**
Lab 02 (Module 3) 
Exercise 1, Task 2, Step 4

#### **Describe the bug**
It states "To locate a specific column, on the Home ribbon tab, select the Manage Columns down-arrow, select the Choose Columns down-arrow, and then select Go to Column."  The Power BI Ribbon has changed. It should say now "To locate a specific column, on the Home ribbon tab, In the Manage Columns group, select the Choose Columns down-arrow, and then select Go to Column."

#### **Screenshots**
New Look:

![New Managed Columns 1](https://user-images.githubusercontent.com/16696370/212766889-1d280d82-7385-4298-94a5-cc27db662ec5.png)

![New Managed Columns 2](https://user-images.githubusercontent.com/16696370/212766907-a0043dc8-5642-4159-9139-0fd85c431006.png)

#### **Expected behavior/Suggested Change**
Update instructions and graphics

#### **Additional context**

Cheers!!!

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by JeffSmalley** [comment]
It looks like your original instructions are right if you have a small monitor. If the application has room, it changes the graphics and adds groups on the ribbon. I guess you can close the issue though maybe add a note on the instructions that the graphic may look different depending on screen size.

**Comment by AngieRudduck** [comment]
Thank you for the awareness. I'll add this to the backlog and if we have several concerns, we'll add a note. 

If ever in doubt, you can search for the feature or direct your students to do so. 

Our goal is that by not having such strict instructions, instructors and students will be able to find the features without impact when product changes are released.
