### ISSUE TITLE
PL-300 02-load-data-with-power-query-in-power-bi-desktop.md Lab Steps

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#145]
#### **Priority**
Medium Priority - Missing Step

#### **Lab/Demo Number/Name**
Lab 02 (Module 3)
Exercise 1, Task 2, Step 5/6 (Missing step in between)

#### **Describe the bug**
There is a step missing between Step 5 and 6.  It forgets to say select the SalesPersonFlag column from the Go Get Column dialog box and click okay

#### **Screenshots**
The Go To Column dialog box:

![New Step Needed](https://user-images.githubusercontent.com/16696370/212768134-572ef5d7-32b2-4f10-b988-2b3915e0ee0d.png)

#### **Expected behavior/Suggested Change**
Add a step after 5.  "Select the SalesPersonFlag column and click OK"

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by JeffSmalley** [comment]
Also, the current Step 6 forgets to say Click OK

![Step 6 Missing Click OK](https://user-images.githubusercontent.com/16696370/212768829-f27c098c-c8c0-4717-9e50-3465d15431cb.png)

**Comment by AngieRudduck** [comment]
Released update Jan 20.
