### ISSUE TITLE
06-design-report-in-power-bi-desktop.md Steps out of order

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#150]
#### **Priority**
Confusing

#### **Lab/Demo Number/Name**
06-design-report-in-power-bi-desktop.md
Exercise 2, Task 2 Steps 1 and 2 

#### **Describe the bug**
The first 2 steps are in the wrong order. 

It states:
1. In the Microsoft Edge browser window, in the Power BI service, in the Navigation pane (located at the left, and it could be collapsed), expand My Workspace.

2.   Open a Microsoft Edge browser, then sign-in at https://app.powerbi.com/.

It should say: 

1.   Open a Microsoft Edge browser, then sign-in at https://app.powerbi.com/.

2. 1. In the Microsoft Edge browser window, in the Power BI service, in the Navigation pane (located at the left, and it could be collapsed), expand My Workspace.

#### **Screenshots**
Add screenshots to help explain your problem.
![Screenshot1](https://user-images.githubusercontent.com/16696370/213565462-282ad9c4-cd4a-4dd6-9049-c92508170636.png)

#### **Expected behavior/Suggested Change**
Change step 1 and 2 around

#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by AngieRudduck** [comment]
Released update Jan 20.
