### ISSUE TITLE
06-design-report-in-power-bi-desktop.md - Wrong instructions

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#151]
#### **Priority**
Confusing

#### **Lab/Demo Number/Name**
06-design-report-in-power-bi-desktop.md
Exercise 2, Task 2 Step 25

#### **Describe the bug**
It States " Select the left icon to exit full screen."

It should say: " Select the right icon to exit full screen."

The added graphic in the instructions is correct.

#### **Screenshots**
Add screenshots to help explain your problem.

![Screenshot 2](https://user-images.githubusercontent.com/16696370/213574275-55384adf-9877-4aee-a036-5e5f847e7198.png)

#### **Expected behavior/Suggested Change**
Change step as outlined above

#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by AngieRudduck** [comment]
Released update Jan 20.
