### ISSUE TITLE
09-create-power-bi-dashboard.md Exercise  Exercise 1 lab step changes

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#156]
#### **Priority**
Breaking

#### **Lab/Demo Number/Name**
09-create-power-bi-dashboard.md Exercise  Exercise 1 lab step changes
Exercise 1, Task 2, Step 2 and 3

Also: Exercise 1, Task 4, Step 4:

#### **Describe the bug**
Step 2 states: "Select New > Dataset. This opens the Get Data page, and under Create new content > Files, select Get."

The interface has changed. It should say: " Click upload, then Browse. 

Step 3 should now state: "Navigate to D:\PL300\Labs\09-create-power-bi-dashboard\Starter folder."

Note: the current step 3 referenced a Solution folder which does not exist. It should be the Starter folder.

Exercise 1, Task 4, Step 4: When I hovered over the Sales and Profit Margin By Month visual, the options that are to show up in the bottom right weren't showing completely because the visuals below were too close. I edited the report and lowered the 2 bottom visuals to give more room and now I can see the options including the Pin Visual option fully.

#### **Screenshots**
Tasks 2 Step 2:
![Lab 8-1 Step 2](https://user-images.githubusercontent.com/16696370/213884367-66f01ee7-e3ff-427d-abe5-473c17adab8d.jpg)

Task 2 Step 3:

![Lab 11 - Exercise 1 Task 2 Step3](https://user-images.githubusercontent.com/16696370/213884486-1d4043af-ead2-4653-b08a-3c197edc5199.jpg)

Task 4 Step 4: (After my report edit and fixed)

![Lab 11 - Exercise 1 Task 4](https://user-images.githubusercontent.com/16696370/213884537-8da90733-6fc8-484d-b00e-569dce599a19.jpg)

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by AngieRudduck** [comment]
Thank you for the catch. Fix will be updated by EOD 2023/2/3.
