### ISSUE TITLE
09-create-power-bi-dashboard.md Exercise 1 lab error

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#157]
#### **Priority**
Breaking

#### **Lab/Demo Number/Name**
09-create-power-bi-dashboard.md Exercise  Exercise 1 lab step changes
Exercise 1, Task 4 Step 20:

#### **Describe the bug**
In the Add Image Tile pane, in the URL box, enter the complete URL found in the D:\PL300\Resources\AdventureWorksLogo_DataURL.txt file, and then Apply.

Adding a data URL for the logo on the dashboard doesn't work. I get an error saying it should start with http:// or https://  
I can't figure out a solution.  :(

I should mention the file DOES exist. I put the "D:\PL300\Resources\AdventureWorksLogo_DataURL.txt" path in Edge and it comes up (just as text however).

#### **Screenshots**

Exercise 1 Task 4 Step 20 Current Instructions:
![Module 11 Lab - Exercise 1 Task 4 Step 20](https://user-images.githubusercontent.com/16696370/213884641-3d47ac9a-16f6-4b53-9614-a989eab38023.jpg)

Exercise 1 Task 4 Step 20 Errors:

![Module 11 Lab - Exercise 1 Task 4 Step 20 Error](https://user-images.githubusercontent.com/16696370/213884661-8af5f27a-6efd-4e18-8c1d-3fe78faa4c55.jpg)

![Module 11 Lab - Exercise 1 Task 4 Step 20 Error 2](https://user-images.githubusercontent.com/16696370/213884667-d24dabe6-bde6-4cc7-a6cf-18dbc917c119.jpg)

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by JeffSmalley** [comment]
I uploaded a JPEG version of the logo to my Azure Blob Storage to get this at least to work for me. Anyone is welcome to use it as a temporary fix until this gets sorted out.   https://cs71003bffd88941878.blob.core.windows.net/pl300/AdventureWorksLogo.jpg

**Comment by olaekdahl** [comment]
You're supposed to put the content of the file in the text box, not the file path itself. The file contains a base64 encoded image. 

In the Add Image Tile pane, in the URL box, enter the complete URL found **in** the D:\PL300\Resources\AdventureWorksLogo_DataURL.txt file, and then Apply.

**Comment by JeffSmalley** [comment]
Thanks..  that works if I read the instructions correctly...   I will close this out.
