### ISSUE TITLE
Perform Data Analysis in Power BI[BUG] (Breaking) (UI update)

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#159]
#### **Priority**
Breaking

#### **Lab/Demo Number/Name**
Exercise 1, Task 3, Step 4 

#### **Describe the bug**
This step currently states:

> Next, we repeat the steps to Get Data from lab 1. From the Home ribbon tab > Data group, select Power BI Datasets.

Two issues:

1) We were not getting data from Power BI datasets in lab 1. Recommend removing that reference as it's incorrect.
2) The UI is different from the one referenced in this text and the screenshot. New UI is below.

#### **Screenshots**
![image](https://user-images.githubusercontent.com/1765732/214677070-6c7ee18f-e0c0-4a9f-adf5-22ec223799e2.png)

**Comment by AngieRudduck** [comment]
@VitalyMCT, thank you for your input. I believe the intent was that we are repeating the Get Data experience. Power BI is able to get data from an almost unlimited number of data sources, and therefore this was likely highlighting it. I can only speculate, as I did not write it. 

I will update this and release changes by EOD 2023/2/3
