### ISSUE TITLE
Metadata in instructions is for DA-100 instead of PL-300

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#16]
The metadata is in the beginning of the lab Markdown and is used by some ALHs to present the Markdown to the students.

Example from the last lab:

![image](https://user-images.githubusercontent.com/1765732/159995251-5eafa3c8-ff62-49fc-8e43-9b25bd9e404c.png)

This is actually Module 12 in PL-300.

**Comment by bpmoring** [comment]
This issue has been addressed.
