### ISSUE TITLE
Power Bi lab 8 

### ISSUE THREAD

**Issue by Yash-malhi** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#160]
So there is an error with Get data seem to be different from the ones in the instructions for power bi service. 
First concern is that the instructions and power bi service to get the dataset are not matching.

Secondly, if using VM to open the solution/starter file which were opening in the past it is not working.

I have added 3 screenshots for reference purpose, tried my best to highlight the concerns.

Please help
![Pl 300 screen error 1](https://user-images.githubusercontent.com/88126448/214678609-2843b0ba-e72a-40b8-81cf-2e1555d0a64b.png)
![Pl 300 screen error 2](https://user-images.githubusercontent.com/88126448/214678624-debf8805-a395-4ea2-bf89-63836e67b52f.png)
![Pl 300 screen error 3](https://user-images.githubusercontent.com/88126448/214678628-3d6563ae-f691-4425-b6c3-2a735101f370.png)

**Comment by arnoldvilleneuve** [comment]
Ouch. I will be in this lab tomorrow afternoon. Thank you for posting.

**Comment by AngieRudduck** [comment]
The behavior changed, and the new way is to **Upload > Browse** and select file. I'll be pushing updates, but closing this duplicate issue now.
