### ISSUE TITLE
Thank you PL-300 Content and Lab Teams

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#161]
Hello 

As this seems to be the only way to contact the PL-300 Content Team I wanted to reach out and say thank you for producing a great course with great labs. You have made significant improvements. 

- 25 slides per module on average instead of 60 or 90!, at 20 slides per hour with a short demo it is a perfect pace

- at 45 minutes some of the labs are a little long but some of the more advanced students were done within 30 minutes

- Jeffrey's screenshot files were very helpful to some of my students but generally speaking everyone got through the labs successfully

I have spoken with a few other MCTs that have taught the course and they were impressed as well. 

Thank you for putting in the effort on the content and the labs so that MCTs can focus on delivering a great learning experience. 

Arnold

**Comment by AngieRudduck** [comment]
Thank you so much for the kind words! We definitely appreciate hearing the positives about the course as well! This is excellent perspective to help us keep aware what specifically works in the course today so that we don't change it.
