### ISSUE TITLE
[BUG] Breaking UI changes and missing file

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#162]
#### **Priority**
Identify if this is a **breaking** bug or not.

#### **Lab/Demo Number/Name**
Lab 11 (Dashboard) 

#### **Describe the bug**
Task 3
Step 2 indicates that the Get Data page is opened, and under Create new content > Files, select Get. The new contents displayed are three cards: Excel, CSV and "Paste or manually enter data".

![GetData](https://user-images.githubusercontent.com/67066583/216130116-ab58f78b-35b9-4e20-a2b9-26c1ed843f26.png)

Step 3 instructs the learner to Select the Local file option, and navigate to D:\PL300\Labs\09-create-power-bi-dashboard\Solution to open the Sales Analysis PBIX file. The file does not exist in the directory.

#### **Expected behavior/Suggested Change**
Update UI change navigation in Step 2
Add file referenced in Step 3

**Comment by AngieRudduck** [comment]
Get data is a duplicate issue. Fix for the file path will be released by EOD 2023/2/3.
