### ISSUE TITLE
[BUG] (Breaking/Non-breaking) Task 3: Get started – Publish the report UI Change

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#163]
#### **Priority**
Instructions do not work anymore for this function

#### **Lab/Demo Number/Name**
Lab 09 Create a Dashboard
Task 3: Get started – Publish the report

#### **Describe the bug**
Instructions are not updated to the new UI

#### **Screenshots**
Add screenshots to help explain your problem.

#### **To Reproduce**
1. Go to Task 3: Get started – Publish the report
2. See that you cannot follow the instructions

#### **Expected behavior/Suggested Change**

Task - to upload data set go to **Workspace** - choose **Upload** then **Browse** - then choose the file (from the file path in the original instructions...

#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by AngieRudduck** [comment]
Closing duplicate issue. Fix will be released by EOD 2023/2/3.
