### ISSUE TITLE
[BUG] (NON-Breaking) Lab 1: Open Power Query Editor

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#167]
At the end of Task 2 the users are in the main Power BI interface.

At the beginning of Task 3 they are expected to be in Power Query Editor.

There should be an extra step in between asking users to click Transform Data to open Power Query Editor. Alternatively, Task 2 could finish with Transform Data click instead of a Load click.

**Comment by arnoldvilleneuve** [comment]
Agreed. 

It is the little things link this makes a big difference when the students are practicing the labs later on their own time after the ILT event is over.

**Comment by AngieRudduck** [comment]
@VitalyMCT and @arnoldvilleneuve I appreciate your devotion to accuracy in the content. For future reference, this is not a breaking bug, as the lab would still work, although instructors would have to advise students who couldn't find their way to Power Query Editor.

- This is not a bug - the steps are accurate. 

- At the end of task 2, you are instructed to click **TRANSFORM DATA**, not **Load**. Transform data opens Power Query Editor. Load only loads in background and leaves canvas view open.


![image](https://user-images.githubusercontent.com/34583336/222468077-cc05c1b5-af44-4906-917c-8debbf2dcb2b.png)


![image](https://user-images.githubusercontent.com/34583336/222467688-0c6e7bf3-2e10-4345-9030-d867783718ec.png)

**Comment by VitalyMCT** [comment]
@AngieRudduck 

The bug is real. However, upon further investigation, it's scoped to GoDeploy's environment. So you are correct in that the instructions here are accurate.

See the current instructions from GoDeploy below. This issue is caused by the forking of official instructions into multiple streams by various ALHs. It's rather unfortunate IMO from a process and QA standpoint.

I will volunteer to raise this to GoDeploy for fixing.

![image](https://user-images.githubusercontent.com/1765732/222474196-d3e58d03-3183-4fd1-9934-c9f3f3d256c5.png)

**Comment by arnoldvilleneuve** [comment]
So does this mean that the lab will not work in a Non GoDeploy environment like Skillable?

**Comment by VitalyMCT** [comment]
Skillable would work fine because they do a real-time pull from GitHub each time instructions are opened. They do not have a disconnected copy loaded in which such issues can crop up.

GoDeploy just fixed the issue after I made them aware of it. They are also apparently looking at improving the process so this type of disconnect is minimized.

**Comment by AngieRudduck** [comment]
This repo is the single source of truth for PL-300 labs. If an ALH isn't using it, then we need to look into why this isn't happening. I'll investigate from my side.
