### ISSUE TITLE
[BUG] (Non-breaking) Design a Report in Power BI Desktop - New UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#168]
Regarding this step:

>To convert the slicer from a list to a dropdown, at the top-right of the slicer, select the down-arrow, and then select Dropdown.

The UI has recently changed, so the instructions need to be updated. Please update per the screenshot below.

![image](https://user-images.githubusercontent.com/1765732/220471908-58c6e3e4-d068-4f94-9f2d-44f798a7b4a1.png)

**Comment by AngieRudduck** [comment]
Image was updated, but not instructions, in last update. Content has been updated now.

"To convert the slicer from a list to a dropdown, navigate to **Visualizations > Format visual > Visual > Slicer Settings > Style**, and then select **Dropdown** from the dropdown menu."
