### ISSUE TITLE
Sales vs Profit Margin is an inappropriate comparison

### ISSUE THREAD

**Issue by sanpietro** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#17]
# Module: 09
##### Step: 03

Description of issue: User is asked to compare Sales and Profit Margin. Those are not compatible comparison as one is an absolute number (Sales) and the other (Profit Margin) is a ratio (which includes the absolute number as the denominator of the calculation). Therefore, the two are not apples-to-applies comparisons. 

To correct this, we would change Profit Margin to Profit, thereby enabling the comparison of two absolute numbers.

**Comment by bpmoring** [comment]
This issue has been noted. We will review with our team.
