### ISSUE TITLE
[Feature] Upgrade Power BI Desktop on ALH VMs to April 2023 release

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#170]
Can we please get this upgrade completed with some urgency? The version currently deployed there is December 2022. Same rationale for getting this done as always (#1).

**Comment by arnoldvilleneuve** [comment]
I agree totally. There is no excuse for such late delays in updating the course material and especially the labs. 
Arnold Villeneuve 

    On Wednesday, April 26, 2023 at 09:41:09 p.m. EDT, Vitaly Livshits ***@***.***> wrote:  
 
 


Can we please get this upgrade completed with some urgency? The version currently deployed there is December 2022. Same rationale for getting this done as always (#1).

**Comment by AngieRudduck** [comment]
We really appreciate your feedback about our labs. We have a regular update schedule and address critical issues as soon as possible. However, it's important to understand that the ALH VM update process is not instantaneous, and our updates aren't driven by the Power BI Desktop release schedule. We know how important it is to stay up-to-date, but updating the labs with every new product release isn't always feasible. We're committed to providing you with the best learning experience, and we hope you understand our limitations in this regard.
