### ISSUE TITLE
[BUG] (Non-breaking) Import instructions for 2nd CSV

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#172]
Regarding this step

> Use the steps **in the previous task** to create a query based on the D:\PL300\Resources\ColorFormats.csv file.

The steps to follow are within the current task (where the 1st CSV is imported), rather than those in the previous task (where the SQL database tables are imported).

**Comment by AngieRudduck** [comment]
Thanks for the catch. Update pending. 

> Repeat the steps to create a query based on the **D:\PL300\Resources\ColorFormats.csv** file.
