### ISSUE TITLE
Adding instructions for signing in to power bi with provided account

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#173]
Is it possible to add an instruction in the lab environment to reference the provided username and password to log in to power bi.

People always get confused and use their personal email, even after mentioning it a lot. They need it infront of them in the instruction steps.

**Comment by AngieRudduck** [comment]
@dtarek1 thanks for the feedback. The lab instructions are used for course instruction and also self-paced learning where credentials are not provided. Therefore, we cannot update this to include your suggestion. This is good feedback for trainer preparation however. Thanks again.
