### ISSUE TITLE
[BUG] (Non-breaking) Instruction not in sync with current UI

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#174]
#### **Priority**
Non-breaking

#### **Lab/Demo Number/Name**
12 - Row level security / Enforce Row-Level Security

#### **Describe the bug**
On exercise 1, task 2, step 4, it says  `On the Home ribbon tab, from inside the Security group, select Manage Roles.` However, Security group is inside the Modeling ribbon, not the Home ribbon. So learners have trouble locating the Manage Roles button. 

#### **Screenshots**
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/46511987/66f2c5d8-60b9-4882-a1c6-6c14e6394832)

#### **To Reproduce**
N/A

#### **Expected behavior/Suggested Change**
On the Modeling ribbon tab, from inside the Security group, select Manage Roles.

#### **Additional context**
N/A

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by Mihai-Ac** [comment]
Hello @SDSTony 

Thanks for flagging this. An update has been made to fix this.

Regards,
Mihai
