### ISSUE TITLE
Improve the instructions "Use original column name as prefix"

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#175]
#### **Which lab or demo?**
Lab 2:  Load Data into Power BI, Task 4: Configure the Product query

#### **Is your feature request related to a problem? Please describe.**
Learners are getting confused with step 7 "Uncheck the Use Original Column Name as Prefix checkbox." They typically already have expanded the DimProductSubcategory column (removed all fields except 2) and clicked ok. But then step 7 asks them to uncheck the box but they are not able to find this checkbox. Learners get lost at this step. 

#### **Describe the solution you'd like**
Make it more obvious what steps need to be taken, for example:
1. combine step 4-6 into just one instruction
2. add screenshot with the checkbox highlighted so it's easier to recognize
3. add instructions to fix the "error" (having wrong column names) - eg click the gear icon from the applied step and remove the name "DimProductSubcategory" name

#### **Additional context**
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/53346841/e9b8e7dc-d916-4b07-9b6b-12be34cf8750)

**Comment by VitalyMCT** [comment]
I agree. This was the number one area of confusion for attendees in my sessions during the past couple of months. Definitely worth refining the instructions around this for clarity.

**Comment by AngieRudduck** [comment]
Thanks to both of you for the valued feedback. I can see how the confusion occurs. Here's the changes I'm submitting:

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/34583336/25772a28-4764-4768-acdb-dae83c9ccb34)

**Comment by VitalyMCT** [comment]
Thanks @AngieRudduck
