### ISSUE TITLE
Filtering on wrong value in Lab 2 - Salesperson Query

### ISSUE THREAD

**Issue by christabelle** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#178]
I've noticed a slight error in Lab 2 - https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/02-load-data-with-power-query-in-power-bi-desktop.md

Task 2: Configure the Salesperson query
Step 6: Select the SalesPersonFlag column header, then select the down-arrow, then FALSE, and click OK.
This action filters the rows to retrieve only employees who are salespeople.

This should be TRUE instead to get the 18 rows as a result.

**Comment by Mihai-Ac** [comment]
Hello @christabelle 

Upon selecting the down-arrow, this is the menu that shows up : 
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/110993710/7d0511c8-80bc-4dbe-ba8c-34444ce4d6cf)


The instructions indicate that one should select **FALSE**. Doing this will remove the check, leaving the filter with only one selection: **TRUE**
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/110993710/6efa2710-8832-4c11-8340-5a1630a480cf)

**Comment by christabelle** [comment]
@Mihai-Ac I think the correct word here should be **UNSELECT** "FALSE" as that is what they are supposed to be doing. Let me know your thoughts!

**Comment by AngieRudduck** [comment]
Verbiage has been updated to align with another similar item:

Locate the **SalesPersonFlag** column, then filter the column to select only Salespeople (that is, **TRUE**), and click **OK**.
