### ISSUE TITLE
Lab 1 - Data Profiling

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#18]
There is a course vs. lab sequencing issue here. 

This lab is for Module 2, whereas the topic of data profiling is only taught for the 1st time in Module 3. So either data profiling should be brought (back?) into the course in Module 2, or this lab portion should be moved over to a latter lab.

**Comment by bpmoring** [comment]
This issue has been noted. However, when updates were made from DA-100 to PL-300 this lab and the corresponding modules were not changed. When the structure is revisited in July, we will look into this.
