### ISSUE TITLE
Upcoming lab changes

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#180]
According to information from the Partner channel there is supposed to be a major PL-300 course update this month. Would the labs be updated as well? If so, on what date would the lab changes be released? 

This is important for MCTs to have visibility into, as we need to coordinate lab versions with class sessions.

**Comment by AngieRudduck** [comment]
Hi @VitalyMCT, thanks for raising the question. Our communications team has the summary of changes and the MCTDLC will have the detailed change log as well. There will be a lab VM update for a newer version of Power BI Desktop, but no major changes to the lab instructions.

**Comment by VitalyMCT** [comment]
@AngieRudduck Thanks for the details. What's the timeline on the lab VM update & the minor changes to the lab instructions?

**Comment by AngieRudduck** [comment]
@VitalyMCT VM updates are scheduled for July 21. in line with the PPT updates. The only changes we've made in the last few weeks are replacing "fields" with "data" to match the UI changes. I don't have anything else specifically slated for the labs, but we work in an iterative process, so as bugs are found or products change, we try to update as quickly as possible.

**Comment by VitalyMCT** [comment]
@AngieRudduck Understood. Would it be possible to get the release notes for the VM update? 

Is anything changing aside from PBI Desktop version? And for PBI Desktop, what release is it being upgraded to?

The current PBI Desktop is July 2023:

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/1765732/ad6ea6b0-87b4-4e20-99ac-5fba67508e93)

**Comment by AngieRudduck** [comment]
That's not something we traditionally have released in advance of the changes, however I'll pass along the idea to our communications team to see how we can best serve the community with timely updates.

Only Power BI Desktop version is changing to June 2023 release. There's a three-week lead time for every update, so it will never be full parity. Our current update schedule is quarterly, unless there's a significant change to the product that requires a sooner update.
