### ISSUE TITLE
Changes in October 6th version

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#186]
This item is similar to https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/issues/180.

The next ILT courseware update is scheduled for October 6th (in 1 week) and it's noted as a "major updated".

Can we please get some release notes for the corresponding lab & VM changes, if any?

**Comment by AngieRudduck** [comment]
@VitalyMCT Hi Vitaly, we appreciate your dedication to delivering high-quality courses to your students. However, this GitHub repository is not the appropriate place to ask for release notes or other information about the upcoming changes. Please refer to the official communication channels, where you'll find the most current and accurate information about the courseware titles and plans.

- https://techcommunity.microsoft.com/t5/courseware-information/latest-courseware-title-plan/ba-p/3897002

- https://techcommunity.microsoft.com/t5/training-services-partner/bd-p/LearningPartnerTraining

Thanks for your cooperation and patience.
