### ISSUE TITLE
Wrong screenshot

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#19]
# Module: 04
##### Step: 09

Screenshot should point to OrderDate fiel
![L03E03T01S09](https://user-images.githubusercontent.com/4288542/160618513-77d66741-2a1b-468c-a4f5-c75c8cf5d07d.jpg)
d

**Comment by bpmoring** [comment]
Issue has been addressed.
