### ISSUE TITLE
[Feature] Renaming of Dataset to Semantic Model

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#194]
Regarding [Datasets renamed to semantic models](https://powerbi.microsoft.com/en-us/blog/datasets-renamed-to-semantic-models/).

This change impacts multiple labs, both in terms of terminology used and various UI-related steps. 

The labs need to be adjusted accordingly so the attendees can complete them with the already-rolled-out PBI Service changes and the upcoming PBI Desktop updates.

**Comment by AngieRudduck** [comment]
@VitalyMCT Thanks for mentioning this change. The updates are already underway and will be committed when ready.
