### ISSUE TITLE
Please add instructions for login in the first launch of power bi

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#196]
Attendees are always confused when launching power bi for the first time as they get asked to log in. They always seem to log in with their personal email which they used for learnondemand.

Might I suggest adding instructions to log in with the email provided to them under the resources tab (maybe add a reference to click on it). Or you can ask them to cancel and add these instructions later on when they get to the publishing steps.

**Comment by AngieRudduck** [comment]
@dtarek1 thank you for the feedback. 

We maintain these uniform exercise instructions for all modalities - self-paced and instructor-led. 

In ILT courses, we value and rely on instructors to provide additional context and guidance to students.

Please let us know how we can support your deliveries without impacting the instructions for self-paced learners. Maybe this would be better suited for informational slides for instructors or the trainer prep guide.
