### ISSUE TITLE
[BUG] (Non-breaking) Missing % format instruction for a decimal value

### ISSUE THREAD

**Issue by arvie993** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#199]
#### **Priority**
Identify if this is a **breaking** bug or not.

#### **Lab/Demo Number/Name**
Create Advanced DAX Calculations in Power BI Desktop/Manipulate Filter Context

#### **Describe the bug**
In Step 11 of the Manipulate Filter context section, the instructions assume that the format will automatically be in the % format. It will actually be in a decimal format and the user will need to change the format using the format pane which is not called out. 

#### **Screenshots**
Add screenshots to help explain your problem.
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/72575271/ca850885-0f73-449b-a83e-629b027d4b24)

#### **To Reproduce**
1. Go to Manipulate filter context section of the lab
2. Perform steps 10 and 11
3. Notice that it will not be in the % format by default

#### **Expected behavior/Suggested Change**
There should be a callout to the fact that the field should be changed to the % format using the format pane.

**Comment by Mihai-Ac** [comment]
Hello @arvie993 

Looking at the instructions, both **Sales % All Region** and **Sales % Country** are to be set up as percentages:
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/110993710/4ce6017c-154d-4926-a5a7-e4016adefa0c)

Regards,
Mihai
