### ISSUE TITLE
Incorrect directory path in lab instructions

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#2]
Some labs instruct students to go to D:\Labfiles\Allfiles. Some labs instruct students to go to D:\PL300.

ALHs seem to be using D:\Labfiles\Allfiles.

The lab instructions should be made consistent internally and consistent with the ALH deployments.

**Comment by bpmoring** [comment]
Thanks, we will make sure to update this on Friday.

**Comment by VitalyMCT** [comment]
@bpmoring I wanted to follow up as it's EOB on Friday.

**Comment by bpmoring** [comment]
All labs indicate D:\PL300.
