### ISSUE TITLE
Issues with Lab 4

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#20]
# Module: 5 - Create Model Calculations using DAX in Power BI
#### Step: 2

You are asked, using DAX, to create a Salesperson table from the existing 'Salesperson (Performance)' table.
The problem is that the Salesperson table already exists. Refer to 1st Screen Shot. Also, if you look at  Lab: 03-configure-data-model-in-power-bi-desktop (at the end of Exercise 1), you see in the list of tables you should have. At that point, the table is still called Salesperson. See screen shot 3.

I believe the problem is that the Renaming of Salesperson to 'Salesperson (Performance)'  was left out in the eariler instructions.

Also, the path to the DAX snippit file is given as D:\PL300\Labs\01\Starter\05-create-dax-calculations-in-power-bi-desktop\Assets\Snippets.txt. It should be D:\PL300\Labs\01\Starter\04-create-dax-calculations-in-power-bi-desktop\Assets\Snippets.txt. Screen Shot 2 shows what the path to the snippet file should be.

Thank you.

Repro steps:

1. Follow the Instructions for Lab 04-Task 2, Step 2.
1.
1
![1](https://user-images.githubusercontent.com/42098682/160650295-52c5c9b2-a39a-4380-87cb-30239935278b.JPG)
![2](https://user-images.githubusercontent.com/42098682/160650394-3dd5a543-fcec-493e-97b1-1085d602d966.JPG)
![3](https://user-images.githubusercontent.com/42098682/160652141-3b2df63f-9b60-4bdf-b994-e7daa7e34328.JPG)
.

**Comment by jamarx2** [comment]
I just found this as well. In DA-100 Lab 4, Exercise 1, Task 2, Step 22, there was a step to rename Salesperson to Salesperson (Performance) which is not performed prior to PL-300 Lab 4, Exercise 1, Task 2, Step 2.

**Comment by jamarx2** [comment]
Lab 04: Create DAX Calculations in Power BI Desktop, Part 1
Exercise 2: Create Measures
Task 1: Create simple measures
Step: 1

Current wording: "_You may recall that in the **Model Data with Power BI Desktop, Part 2** lab..._"

Should be "_You may recall that in the **Model Data in Power BI Desktop** lab..._"

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/83473157/160884350-a9c04f47-04b6-468f-b986-0a69c5b43602.png">

**Comment by jamarx2** [comment]
Quick Measures for Profit and Profit Margin are created in DA-100 Lab 3, Model Dats in Power BI Desktop, Part 1, Exercise 4, Task 1. These same measures are not created in PL-300 but are referenced in Lab 6, Design a Report in Power BI Desktop, Part 1, Exercise 1, Task 4, Step 26 and Task 5, Step 8.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/83473157/160894759-edf0bedc-7668-4e76-bd6a-e4d42049b653.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/83473157/160894849-ef3bc444-232b-4337-aa61-1589764c5a4d.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/83473157/160894925-e10a38bc-4892-42c7-a77b-a4c91356ac5c.png">

**Comment by NMitjmgComputer** [comment]
Hello All,

Just hoping that MS gets their lab instructions updated per all the comments people have entered.

Thank you.

**Comment by Jason-M-Richards** [comment]
This error is happening because the original DA-100 lab instructions included a part 2 that wasn't added to this version of the course. My suggestion, until they add the proper instructions, is to guide students to the instructions from the original github part 2 instructions and add about 20 minutes to total lab time for that module 

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/04-configure-data-model-in-power-bi-desktop-advanced.md

**Comment by weslbo** [comment]
Any update on this?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by carloscastiglioni-uy** [comment]
@MOC-Labs-Review did you see this problem?

If so, can you please tell us where the steps of the laboratory are found with the link cited below (DA-100 course laboratory) in the new PL-300 course?

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/04-configure-data-model-in-power-bi-desktop-advanced.md

Thank you.

**Comment by bpmoring** [comment]
This issue has been resolved in the latest update.
