### ISSUE TITLE
[BUG]  Breaking / Sensitivity Label error message when attempting to open Lab 01 Sales Analysis.pbix file

### ISSUE THREAD

**Issue by DerekFoster1976** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#205]
#### **Priority**
Breaking

#### **Lab/Demo Number/Name**
Lab 1 (possible others)

#### **Describe the bug**
When attempting to load the starter lab 01 Sales Analysis.pbix, a sensitivity label error message pops up and prevents students from loading the .pbix file. This is affecting around half the students in my class using Skillable PL_300 labs and also outside of the Skillable sandbox on my own personal machine.

#### **Screenshots**
<img width="695" alt="sensitivity label error" src="https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/2176463/390f6258-a93d-46af-a83b-19b1ff5e6d7d">

#### **To Reproduce**
1. Open Power Bi Desktop
2. File>Open Report
3. Select load Allfiles\Labs\01-prepare-data-with-power-query-in-power-bi-desktop\Starter\Sales Analysis.pbix
4. See error Sensitivity label error as above screenshot.

#### **Expected behavior/Suggested Change**
The selected .pbix file should load as normal with all elements viewable with no sensitivity label error.

#### **Additional context**
It is not clear to me why only some of my students are experiencing this issue in the PL-300 Skillable labs environment, however I also experience it on my own personal machine using the files from the Github repo. Skillable labs also download the lab files directly from the repo.

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by DerekFoster1976** [comment]
I'll close this one down as resolved. The sensitivity label message that pops up when opening- Allfiles\Labs\01-prepare-data-with-power-query-in-power-bi-desktop\Starter\Sales Analysis.pbix - does not cause any apparent issues when progressing through to completion of the lab.

**Comment by AngieRudduck** [comment]
@DerekFoster1976 thanks for the feedback. This is not a breaking bug, however it is in the backlog to resolve.
