### ISSUE TITLE
Collapsing and reopening the data pane no longer resets the content in LP 04, Create additional measures

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#207]
In LP 04, Create DAX Calculations in Power BI Desktop, Create additional measures, Step 14, it states "At the top-right corner of the Data pane, collapse and then expand open the pane. Collapsing and reopening the pane resets the content" [p1].
Upon testing in Power BI, it appears that collapsing and reopening the pane does not reset the content as stated. Unsure if this is a bug or an update that's removed the feature from PowerBI.

[p1]

![image-1](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/94069201/4c0a0faa-cfb1-447f-838d-9e19f0299938)

**Comment by afelix-95** [comment]
Thank you for pointing it out! Indeed, now reopening the pane is not required to reset its contents anymore, as it auto updates after each change. So, after you hide the **TargetAmount** column in step 6, the **Targets** table automatically goes to the top of the list as only the **Target** measure is visible at that point. Step 14 will be removed as it is currently obsolete.
