### ISSUE TITLE
[BUG] (Non-breaking) UI change for opening reports menu

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#208]
#### **Priority**
Not breaking

#### **Lab/Demo Number/Name**
Most labs

#### **Describe the bug**

There's been a slight UI change and the version of PBI Desktop deployed on ALH VMs has different menus compared to those referenced in the instructions. 

* Current lab step: To open the starter Power BI Desktop file, select the File > Open Report > Browse Reports.
* Lab step to align to UI: To open the starter Power BI Desktop file, select the File > Open > Browse this Device.

#### Screenshot

Current UI:

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/1765732/1e9d143e-b005-4205-8196-e148b62e8c6d)

**Comment by VitalyMCT** [comment]
@AngieRudduck Can you please process this issue & the other ones that accumulated in this project? Thank you.

**Comment by AngieRudduck** [comment]
@VitalyMCT Thank you for the mention. The issues are currently in backlog to resolve.

**Comment by VitalyMCT** [comment]
@AngieRudduck Can you please share some timelines around getting the outstanding items addressed? Issue resolution in this repo has been on hold for 3 months (from 1st week of February), which is quite a long time for customers to wait. Previously issues were typically addressed within a few days of them being reported.

**Comment by AngieRudduck** [comment]
fixed in PR #214

**Comment by VitalyMCT** [comment]
Thanks @AngieRudduck , much appreciated! Just in time for my next session starting in 14 minutes :)
