### ISSUE TITLE
[BUG] (Non-breaking) Dataset menu option

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#209]
#### **Priority**
Not breaking

#### **Lab/Demo Number/Name**
Data Analysis in Power BI

#### **Describe the bug**
The step in the instructions is 

>In the Home ribbon, select Get Data > Power BI **semantic models**

It should instead be as follows to align with the GUI:

> In the Home ribbon, select Get Data > Power BI **datasets**

Although most labels in Power BI platform have already been updated from "dataset" to "semantic model", this is not one them.

**Comment by AngieRudduck** [comment]
fixed in PR #214
