### ISSUE TITLE
More issues with Lab 4

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#21]
# Module: 05 Create Model Calculations Using DAX.
#### Step: 7

You are asked to Delete the Inactive Relationship between Salesperson (Performace) and Sales. Problem is, there is no such inactive relationship. See screen shot 4.

In DA-100 there were TWO labs on modeling relationships. PL-300 has only the 1 lab on modeling relationships. But, to me, it looks like some steps from the 2nd lab on Modeling found in DA-100 (Model Data i Power BI Desktop, Part 2) need to be added to the PL-300 lab on modeling.

Thank you.

Repro steps:

1. Follow the lab instructions
1.
1
![4](https://user-images.githubusercontent.com/42098682/160657830-a0c9962f-1bc4-4160-896b-1cb45bd08716.JPG)
.

**Comment by VitalyMCT** [comment]
Thanks for bringing this up. I wonder if asking students to use the Starter .pbix for this lab (instead of their own file from the previous lab) would be the temporary workaround for this issue, until the instructions are fixed.

**Comment by NMitjmgComputer** [comment]
Hello Vitaly and all else interested in this topic ...

 

I agree with you that students, until the lab instructions are fixed, start with the appropriate starter .pbix. In looking at the labs, that is what I have had to do.

There were additional modeling "omissions" after my original post e.g., missing Profit and Profit Margin calcualted measures in the (base) Sales table.

 

In DA-100, as I recall, those two measures were added as Quick Measures. These measures are needed on some of the report pages. Where in the lab instructions were they added??

 

So, again, until the lab instructions are updated/revised/fixed, ask students to begin with the appropiate Starter .pbix beginning with the lab where they need to develop DAX formulas.

 

Thank you.
 

John Geiger
MCT

 
 

Sent: Tuesday, March 29, 2022 at 3:04 PM

**Comment by Jason-M-Richards** [comment]
This error is happening because the original DA-100 lab instructions included a part 2 that wasn't added to this version of the course. My suggestion, until they add the proper instructions, is to guide students to the instructions from the original github part 2 instructions and add about 20 minutes to total lab time for that module

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/04-configure-data-model-in-power-bi-desktop-advanced.md

**Comment by jdtraining** [comment]
40 days since this error was reported. Is anybody from Microsoft reading this?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by jdtraining** [comment]
> MOC Labs Review did not experience this issue.

Well you did not look very well.

Just compare the Model view in the solution file from LAB 3 to the Model view in the Starter File of LAB 4. These files should be the same. They are not. Microsoft really messed up the Lab instruction and files with the change from DA-100 to PL-300. I just finshed a group and it's kinda embarrasing. 

Jeroen Dekker
MCT

**Comment by carloscastiglioni-uy** [comment]
> MOC Labs Review did not experience this issue.

Please see in the following screenshot the missing lab in the present version that existed in the version of the DA-100 course

![image](https://user-images.githubusercontent.com/106550603/171038701-0f0f72b3-48db-4e1d-8096-5d0a8613c84b.png)

**Comment by jdtraining** [comment]
![image](https://user-images.githubusercontent.com/67203087/171046980-de2294d7-e8e0-4822-8bef-31cf0531ca37.png)

**Comment by jdtraining** [comment]
> MOC Labs Review did not experience this issue.

Model at end of LAB3 Pl300 (Solution File)
![lab3 pl300](https://user-images.githubusercontent.com/67203087/171048811-f1efef2f-e3d3-47a8-9193-2e3723526a69.png)

Model at start of LAB4 Pl300 (Starter File)

![lab4 pl300](https://user-images.githubusercontent.com/67203087/171048860-4bcdd65b-e1f4-4375-b266-427f8179a44e.png)

**Comment by carloscastiglioni-uy** [comment]
Correct @jdtraining, this is because in the PL-300 course, the following laboratory of the DA-100 course is missing:

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/04-configure-data-model-in-power-bi-desktop-advanced.md

**Comment by bpmoring** [comment]
Instructions have been added to bridge the gap.
