### ISSUE TITLE
[Feature] Update Power BI Desktop on ALH VM to May 2024 release

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#217]
Please see #1 for additional context and rationale for keeping the app up-to-date for this course.

The ALH VMs currently have the November 2023 built, making them 5 releases behind (every month except January has a release):

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/1765732/c6417589-4862-4d86-9b6e-1065c3a440e7)

As before, the app update will need to coincide with a lab instruction update.

**Comment by AngieRudduck** [comment]
VM will be updated and made available by July 12th with updated Power BI Desktop version (June 2024).

**Comment by VitalyMCT** [comment]
Thanks @AngieRudduck. 

When would the corresponding instruction update be released? I would like to verify everything on our side (i.e. new lab VM + instructions) before the next session run.

**Comment by AngieRudduck** [comment]
Hi Vitaly, I can only share the process that we have. We coordinate a date to update instructions when the Skillable VM will be updated. There's a process during that time, which includes updating the VM for additional ALH to use. The date here is July 12th. Instructions and VM updates are done in parallel when instructions are dependent on VM updates.

**Comment by VitalyMCT** [comment]
Perfect, thank you. I will be on the lookout for the instructions update that Friday. It will give an opportunity to complete preparation for sessions that start the week after.
