### ISSUE TITLE
Incorrect path in "Create DAX Calculations in Power BI Desktop, Part 1" lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#22]
Lab is referencing "D:\PL300\Labs\0**5**-create-dax-calculations-in-power-bi-desktop\Starter"

This path does not exist.

It should be referencing "D:\PL300\Labs\0**4**-create-dax-calculations-in-power-bi-desktop\Starter"

Edit: Recommend verifying all labs for similar issues.

**Comment by VitalyMCT** [comment]
Indeed other labs have similar issues. 

Example: https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/06-design-report-in-power-bi-desktop.md is referencing 07 folder instead of 06.

**Comment by bpmoring** [comment]
This issue has been addressed.
