### ISSUE TITLE
[MISSING RESOURCE] (Non-breaking) Access database link unavailable to follow along

### ISSUE THREAD

**Issue by kawaremu** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#220]
#### **Non breaking Bug**
This is not a **breaking** bug.

#### **Data Analyst Plan | How to manage your data relationships**
[Create and use analytics reports with Power BI](https://learn.microsoft.com/en-us/training/modules/model-data-power-bi/2-how-to-manage-data-relationships)

#### **Description of the bug**
The follow-along Access database [link](https://baglabspublic.azureedge.net/baglabspublic/PowerBI_sample.accdb) is not available

#### **Screenshots**
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/58731392/1b7992df-3e77-4bfc-9458-4eee400025a6)

**Comment by AngieRudduck** [comment]
This bug is not related to PL-300 ILT exercises, and has been routed to the appropriate location.
