### ISSUE TITLE
[BUG] (Breaking) Credentials for GitHub data source get reset

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#226]
This issue is in https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/Labs/02-load-data-with-power-query-in-power-bi-desktop.md

The step is:

![image](https://github.com/user-attachments/assets/656e175c-ba47-40ad-b179-8d50edcc4fbd)

When the users go to the corresponding file the Edit Credentials window appears instead of the data preview. Instructions should be added for the attendees to click Edit Credentials and confirm Anonymous authentication:

![image](https://github.com/user-attachments/assets/f056af5c-6649-439d-9bd6-696bd1f91e42)

The issue is reproducible in Skillable's ALH environment.

**Comment by AngieRudduck** [comment]
@VitalyMCT thanks for the catch.

@afelix-95 please confirm.

**Comment by VitalyMCT** [comment]
@afelix-95 Can this please be patched up via an instruction (or VM) update? I have had several groups of attendees run into this issue this week.

**Comment by afelix-95** [comment]
A note was added to the lab instructions to cover this extra connection step.

**Comment by VitalyMCT** [comment]
Thanks @afelix-95 !
