### ISSUE TITLE
[BUG] (Breaking) Out of date path in DAX lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#227]
This impacts https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/Labs/04-create-dax-calculations-in-power-bi-desktop.md

The file path in the instructions is carried over from the previous version of the labs:

![image](https://github.com/user-attachments/assets/2f4f9493-d07f-4d09-9dd5-9f461f1a493c)

The file path in the current version is:

![image](https://github.com/user-attachments/assets/025abb7d-ea9f-4ebc-a4a7-41a78f56b819)

Please align instructions accordingly.

**Comment by AngieRudduck** [comment]
This has been updated.

**Comment by VitalyMCT** [comment]
Thanks @AngieRudduck . I appreciate the quick turnaround on this item.
