### ISSUE TITLE
[BUG] (Non-breaking) Out of date screenshot

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#229]
This is in reference to https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/Labs/02-load-data-with-power-query-in-power-bi-desktop.md

The following screenshot is from the previous version of the labs and should be updated. The 2nd data source is GitHub rather than the D: drive.

![02-load-data-with-power-query-in-power-bi-desktop_image74](https://github.com/user-attachments/assets/3d3a87bc-e6b8-4e27-8bd2-c611bf78150d)

**Comment by afelix-95** [comment]
Screenshot updated.
