### ISSUE TITLE
Screen Shots for Formatting Reports Need to be Updated

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#23]
# Module: Design Reports in Power BI Desktop
#### Step: 17

Please see 1st screenshot. This is from the lab instructions for  06-Design-Report-in-Power-BI-Desktop  but applies to any lab instructions that ask for report formatting. 

Since the lab instructions were developed, MS has updated PBI Desktop and changed the icon for the format pane. The lab (Go Deploy hosted) is using the February 2022 build of PBI Dekstop.  __All__ the lab instructions still show the "Paintbrush roller" icon instead of this new icon. See 2nd screenshot. That is one issue.

The more challenging issue is that the PBI Desktop seems to have come up with different categorizations of the properties. For example, the 3rd screenshot is from Exercise 1, Task 4, Step 18 on formatting a slicer. It shows General and Selection controls.

But, as you can see from the 4th screenshot, the PBI Desktop is now calling these controls "Visual" and "General".  Except for using the search capabiity built into the Visualization Format pane, someone is not likely to be able to follow the lab instructions if they are trying to locate a Visualation Format property unless they _Search_ for that property. 

Anyway, someone needs to go through the lab instructions that concern formatting Visualizations and update them for the newer release of the PBI Desktop. 

The following article from MS on the new Format pane might be of help: [](url)https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane

Thank you.

Repro steps:

1.
1.
1
![Format_1](https://user-images.githubusercontent.com/42098682/160852158-93d8f6b1-3563-45a6-a354-3c6b65f596e4.JPG)
![Format_2](https://user-images.githubusercontent.com/42098682/160852933-b2409bb0-faf8-43c1-b52d-f3f31cc694dc.JPG)
![Format_3](https://user-images.githubusercontent.com/42098682/160853945-7a54b15c-84e0-4959-8bd0-679507c6b035.JPG)
![Format_4](https://user-images.githubusercontent.com/42098682/160854543-d0ae099d-5e94-4095-9281-86c7b2268eab.JPG)
.

**Comment by VitalyMCT** [comment]
This is one of the manifestations of https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/issues/1

**Comment by NMitjmgComputer** [comment]
@VitalyMCT Vitaly, thank you for the update.

For the record, I am using ALH Go Deploy which is using the February 2022 build of the PBI Desktop. But, as is already well documented in this forum, the Lab instructions on GitHub and, thus in Go Deploy, need  to be updated for the Data Model and the Report formatting.

I appreciate all your comments @VitalyMCT. Am very new to using GitHub so appreciate what you and your colleagues are saying on PL-300.

Thank you.

**Comment by VitalyMCT** [comment]
Yes, I am on Go Deploy too this week.

**Comment by NMitjmgComputer** [comment]
After my original post and reading the comments, I went back and looked again the MS documentation on the New Format Pane as given in the URL of my original post. 

See the screenshot on How to turn off the New Format Pane preview feature.
![Format_WorkAround](https://user-images.githubusercontent.com/42098682/160881840-0e7ac653-569f-4e34-8a2a-5884b006afc9.JPG)

Just tried it out in the Go Deploy lab .. and it works. The lab instruction screen shots now "match" what is in the PBI Desktop.

So, this seems to be a workaround until MS "updates" the GitHub instructions to match the New Format Pane.

Thank you.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by bpmoring** [comment]
All visuals have been updated.
