### ISSUE TITLE
[Feature] Restore Automatic Download

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#231]
The new version of each lab's instructions contains links to download a ZIP file from GitHub. The previous version had integration done by each ALH (ex. Skillable, GoDeploy, etc.). that performed this download automatically, via a 1-button click by attendees.

The latter option provided a superior experience for the lab attendees, letting them focus on learning Power BI instead of downloading and extracting ZIP files.

Can ALHs please be authorized by the PL-300 lab author(s) to re-add that automatic download option to the labs? 

It should be easy to do, as the necessary codebase is already in place. Skillable advised me it needs that authorization from Microsoft to restore the download button.

**Comment by AngieRudduck** [comment]
@VitalyMCT Thanks for your feedback. Our labs are created for modularity to allow them to used in multiple formats and platforms. We understand the transition to the completely modular format will take some adjustment from instructors and may require a bit of extra time for students. However, this change was in accordance with WWL standards. You can alternatively download the Allfiles.zip folder for all lab files in a single folder, and adapt the instructions to suit your needs.

**Comment by VitalyMCT** [comment]
@AngieRudduck To clarify, neither modularity nor new version are not being questioned within this ticket. Those are both wonderful.

The ask is to simply approve Skillable's (or other ALHs) 1-button addition to make the download process as user-friendly for attendees as it was before. 

My additional research shows that other ALHs, including GoDeploy, have retained the user-friendly experience with the new version. 

Skillable removed it because of an apparent misunderstanding that it's somehow incompatible with the new version (it's fully compatible). They apparently require Microsoft's approval to re-enable it.

Thank you.

**Comment by AngieRudduck** [comment]
I understand, Vitaly. The removal of the button in Skillable was not a misunderstanding, but a decision from WWL. We cannot control how other ALH design their UI. However, by not adhering to the new experience, the students won't be able to follow along with the instructions as is due to different folder locations.

**Comment by VitalyMCT** [comment]
@AngieRudduck The button will be simply come before the new instructions, same as before.

Students will be able to follow along with the instructions as the folders will remain 100% the same. The script behind the button simply downloads the files for the student :)

Please reference GoDeploy's current, automated version for an example of an implementation that's both compatible with the new version of the instructions and user-friendly.

**Comment by AngieRudduck** [comment]
@VitalyMCT That's something for Skillable to decide then, and I'll reach out to them.

**Comment by VitalyMCT** [comment]
Thanks @AngieRudduck, much appreciated. Your understanding now matches my understanding :)
