### ISSUE TITLE
[BUG] (Non-breaking) Minor update to field naming in visuals

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#232]
This impacts https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/Labs/06-design-report-in-power-bi-desktop.md. It may also impact the 2nd reporting lab.

The version of Power BI Desktop deployed to ALHs has slightly different behaviour compared to that documented in the instructions (which is from the previous version of Power BI Desktop).

Here's the corresponding section:

![image](https://github.com/user-attachments/assets/08d4dbfc-cbdd-4330-9e9c-907c92afba57)

The current version of Power BI Desktop adds "Sum of" as a prefix to field name in the visualization. 

Please update this step and review + update other steps for similar scenarios.

**Comment by AngieRudduck** [comment]
@VitalyMCT is the problem that the image does not exactly match the experience when you add the field to the well?

**Comment by VitalyMCT** [comment]
@AngieRudduck Yes, it's the image and also the fact that the instructions do not refer to the "Sum of" prefix, they just say "fields are assigned". I had a few groups of attendees flag this to my attention ... they thought they may have been doing something incorrectly.

**Comment by VitalyMCT** [comment]
Here's another instance of the same issue where attendees are reporting confusion. This one is from the 1st DAX lab.

![image](https://github.com/user-attachments/assets/a8824dae-fbd1-45f6-b756-40631b92c571)

The screenshot on step 2 is already updated, so it confuses folks to see the unexpected screenshot in step 6.

![image](https://github.com/user-attachments/assets/70ddd10d-c01a-4d67-b559-65821611885c)

**Comment by AngieRudduck** [comment]
@afelix-95 Can you add this to your backlog please?
