### ISSUE TITLE
[BUG] Lab 4: Starter-SAles Analysis.pbix file issue

### ISSUE THREAD

**Issue by igor-lekontsev** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#237]
For the 4th Lab 'Introduction to DAX in Power BI Desktop' I believe the file is corrupted or empty. It looks like it was updated earlier today and now anytime you download it and it goes to load in the program desktop, it gives an error that says "........ can't be opened. Either the file is encrypted or corrupted.".

**Comment by afelix-95** [comment]
Thanks for catching that. It was an encryption issue, should be working now.
