### ISSUE TITLE
Script to Update June 2020 Sales data needs to be fixed

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#24]
# Module: 08-create-power-bi-dashboard
#### Step: 2

Not sure if this issue belongs here on GitHub but it is an issue.

This Lab Exercise/Task/Step has you run a PS script which, in turns, run an .sql file to add Junes 2020 Sales data. 
Because of the directory change from DA-100 to PL-300, the .sql file "breaks". See screen shot 1.
![ScriptIssue_1](https://user-images.githubusercontent.com/42098682/160887999-ceadc0be-6793-4b46-8e5b-66dcbda1ac7d.JPG)

The fix is easy enough. See screenshot 2 
![ScriptIssue_2](https://user-images.githubusercontent.com/42098682/160888094-08a67e43-911b-4f12-89c6-306ff616b4fa.JPG)

and 3
![ScriptIssue_3](https://user-images.githubusercontent.com/42098682/160888595-9bf5ffb6-5e97-4dee-9aec-9010310a0873.JPG)
.

Again, the fix is easy enough but how do we walk the students through this? 

The resolution needs to be in the .sql script downloaded from GitHub.

Repro steps:

1.
1.
1.

**Comment by VitalyMCT** [comment]
This is the script: https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Allfiles/Setup/Scripts/UpdateDatabase-2.sql

**Comment by NMitjmgComputer** [comment]
@VitalyMCT 
So, _who has the responsibility to modify the script and make it "officia"__ Am still new to all this.

Thank you.

**Comment by VitalyMCT** [comment]
@NMitjmgComputer Microsoft :)

We only have read-only access to this repo, unfortunately.

**Comment by NMitjmgComputer** [comment]
Hello Vitaly,

 

Thank you for your reply. I am not surpised that MS would restrict access to the repo.

 

At least we know how to handle in our classes until MS "fixes" things.

 

Thank you again for all your comments and help!
 

John Geiger
MCT

 
 

Sent: Wednesday, March 30, 2022 at 2:12 PM

**Comment by bpmoring** [comment]
Making the requested change. I will close, but if you continue to see this issue, please reopen.
