### ISSUE TITLE
[BUG] (Non-breaking) Obsolete setting change in Visual Calculations lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#243]
Regarding

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/df839b9d-1558-445a-ac7d-5f90d506ec06">

Per official Power BI documentation on Microsoft Learn, this step was only needed in old versions of Power BI Desktop. Microsoft has ALHs standardized on the October 2024 release as of November 22nd.

From https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-visual-calculations-overview:

<img width="786" alt="image" src="https://github.com/user-attachments/assets/0dd967cd-033d-4f1f-8924-d205b8f262db">

**Comment by afelix-95** [comment]
Thank you for pointing that out! Instructions are now updated.

**Comment by VitalyMCT** [comment]
Thanks @afelix-95
