### ISSUE TITLE
Instructions are missing to set the Alert in the PBI Service when the Sales card changes on the Dashboard

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#25]
# Module: 08
#### Step: 5

The instructions have been left out on how to set the Alert on the dashboard.
![Alert_1](https://user-images.githubusercontent.com/42098682/160890218-d2ca8e67-9e76-4442-9376-0f51633a2131.JPG)

This is minor, in my view, and we can explaing how Alerts work. But, the instructions should be updated.

Thank you.
Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
This issue has been addressed.
