### ISSUE TITLE
Issues with Lab 6

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#26]
# Lab:  06 Design a Report in Power BI Desktop, Part 1
#### Step: 26

Quick Measures for Profit and Profit Margin are created in DA-100 Lab 3, Model Dats in Power BI Desktop, Part 1, Exercise 4, Task 1. These same measures are _not_ created in PL-300 but are referenced in Lab 6, Design a Report in Power BI Desktop, Part 1, Exercise 1, Task 4, Step 26 and Task 5, Step 8.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/83473157/160894759-edf0bedc-7668-4e76-bd6a-e4d42049b653.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/83473157/160894849-ef3bc444-232b-4337-aa61-1589764c5a4d.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/83473157/160894925-e10a38bc-4892-42c7-a77b-a4c91356ac5c.png">

**Comment by jamarx2** [comment]
# Lab: 06 Design a Report in Power BI Desktop, Part 1
## Exercise 1: Create a Report
### Task 6: Design Page 3
#### Step: 7

Measures for Target, Variance, and Variance Margin are created in DA-100 Lab 5, Create DAX Calculation in Power BI Desktop Part 1, Exercise 2, Task 2, Step 10. These same measures are not created in PL-300 but are referenced in Lab 6, Exercise 1, Task 6, Step 7.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/83473157/160899551-49eec355-178c-4468-b667-129bc92f60ef.png">

**Comment by NMitjmgComputer** [comment]
I have noticed this as well.

The only way I could quickly get around the problem was by opening the relevant Starter .pbix so that the Model and the Measures, all of them, would be there.

Thank you @jamarx2 for posting this.

**Comment by jamarx2** [comment]
Thanks @NMitjmgComputer  - apologies for my edits in your Lab 4 thread. I've been an active lurker until today.

**Comment by Jason-M-Richards** [comment]
This error is happening because the original DA-100 lab instructions included a part 2 of the modeling lab that wasn't added to this version of the course. My suggestion, until they add the proper instructions, is to guide students to the instructions from the original github part 2 instructions and add about 20 minutes to total lab time for that module (modeling)

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/04-configure-data-model-in-power-bi-desktop-advanced.md

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by carloscastiglioni-uy** [comment]
MOC Labs Review: please see in the following screenshot the missing lab in the present version that existed in the version of the DA-100 course

![image](https://user-images.githubusercontent.com/106550603/171038322-9cd275bd-12b6-4404-8f60-bf753cd36d1c.png)

**Comment by bpmoring** [comment]
These instructions have been added back into the lab to remove any continuity issues.
