### ISSUE TITLE
Minor Issue with Lab 9

### ISSUE THREAD

**Issue by NMitjmgComputer** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#27]
# Module: 09-Perform-Data-Analysis-in-Power-bi-desktop
#### Step: 3

Description of issue

Please see attached screen shot. Shouldn't the instructions tell the student to Publish to their My "Workspace" before closing the PBI Desktop? This is picky, granted, but for the sake of clarity ...
![Publish_1](https://user-images.githubusercontent.com/42098682/160905007-3480faa6-4a24-47e2-b3c2-02b82977c00e.JPG)

1.
1.
1.

**Comment by bpmoring** [comment]
This issue has been addressed.
