### ISSUE TITLE
Perform Data Analysis in Power BI Desktop - Obsolete Note

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#28]
> You’ll now create **four** report pages, and on each page you’ll work with a different visual to analyze and explore data.

DA-100 had four report pages.

This course has two report pages.

The note should be corrected accordingly.

**Comment by NMitjmgComputer** [comment]
@VitalyMCT  
Have found this myself. Am glad you made the note Vitaly.

Wonder when MS is going to get all these notes incorporated and issues fixed?

**Comment by bpmoring** [comment]
This issue has been addressed.

**Comment by VitalyMCT** [comment]
@bpmoring Would you mind describing how it's been addressed? The instructions are the same as before.

**Comment by bpmoring** [comment]
I am currently making changes in VS and will be pushing the updates through today.
