### ISSUE TITLE
Issue with Lab 10

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#30]
# Module: 12
##### Step 6

Incorrect starter file name. Should be **10-row-level-security** not **12-row-level-security**.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/83473157/161328946-f163c1b4-08ac-4c9f-825b-011ddea633aa.png">

**Comment by bpmoring** [comment]
This issue has been addressed.
