### ISSUE TITLE
Reference in readme goes to old course

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#32]
Page: https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/readme.md

Issue:

> Do you need a refresher on which labs go with which module? - Check out the [GitHub Page](https://microsoftlearning.github.io/DA-100-Analyzing-Data-with-Power-BI/)

**Comment by bpmoring** [comment]
This has been updated.
