### ISSUE TITLE
Version file is out of date

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#33]
The software listed there seems to be for an old DA-100 version.

https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Allfiles/Setup/Version.txt

**Comment by bpmoring** [comment]
Updated the desktop version number.

**Comment by VitalyMCT** [comment]
@bpmoring 

I think there is a bit more to the update:

1) There is PBI Report Builder on the VMs Microsoft provides to the ALH, correct? If so, that software should be removed from the inventory.
2) The PBI Service version is old and I am unsure what's the value of keeping it.

**Comment by bpmoring** [comment]
Agreed, I just updated and removed the extra information. Thanks!
