### ISSUE TITLE
Lab 1, Ex 1, Task 3, Step 9 - confusing comment

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#34]
# Module: 02
#### Step 9

 As written, the Transform Data button is outlined in red and the instructions say:
 
> 9. To apply transformations to the data of the selected tables, click Transform Data.
> 
> You won’t be transforming the data in this lab. The objectives of this lab focus on exploring and profiling the data in the Power Query Editor window.

"You won't be transforming the data in this lab..." is technically correct, but confusing. I don't think those lines are necessary or it could be clearer that we access PQ via the Transform Data button and we'll actually transform the data in Lab 02.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/83473157/162789316-6b54389f-13ed-4024-bf80-f508ea59599e.png">

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
No update needed.
