### ISSUE TITLE
Lab #04

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#35]
#### Step 6

Description of issue
Please update the references to the files. Students takes alredy completed file.

Repro steps:
instruction said: 
In the Open window, navigate to the _D:\PL300\Labs\05-create-dax-calculations-in-power-bi-desktop\Starter_ folder.
should be
In the Open window, navigate to the _D:\PL300\Labs\0**4**-create-dax-calculations-in-power-bi-desktop\Starter_ folder.

**Comment by bpmoring** [comment]
This issue has been addressed previously. Please make sure you are using the latest version of the lab.
