### ISSUE TITLE
ALL MODULES LABS

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#37]
# Module: 00
#### Step: 00

Description of issue

**The issue is that some paths in the Starter and Solution files refer to DA100 in the file path and causes errors when the learner uses these files.**

Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
This issue has been resolved with the latest commit.
