### ISSUE TITLE
Demo 11 - UpdateDatabase-LoadAdditionalSales.ps1 fails

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#38]
# Module 11: Manage Files and Datasets in Power BI
### Step: 41

PL-300 Demo Instructions, page 18, step 41 reads: "Right-click the D:\PL300\Demo\Resources\UpdateDatabase-LoadAdditionalSales.ps1 file, and then run with PowerShell."

Red error messages appear indicating a failure to access the database due to the server name being DATA-AI instead of Adventureworks. When I edited to change the server name, it worked.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
Could not duplicate issue.
