### ISSUE TITLE
Some (possibly all?) lab files still refer to D:\DA100\ path for data files (Reopening this issue)

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#39]
Perhaps I'm missing something -- I flagged this issue (#12 ), and it was closed, but it is clearly not resolved:

![image](https://user-images.githubusercontent.com/7502186/164124806-094e5a23-86cf-4b8a-bffa-6e2c56858740.png)

That is the load screen for the Lab 1 solution -- as you can clearly see, the file is looking for data files in a directory called D:\DA100, but in this environment it _should_ be D:\PL300.

**Comment by bpmoring** [comment]
This issue has been addressed with the latest commit. If you find another issue, please identify and open a ticket.
