### ISSUE TITLE
Different instructions on Github and in Lab environment

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#40]
There is different content on Github and in Lab environment

![Lab4](https://user-images.githubusercontent.com/4288542/165508571-81f19e3d-8fb2-4f61-88a9-d588b511e093.png)
![Lab5](https://user-images.githubusercontent.com/4288542/165508581-5e7c245a-640e-44e3-8f94-25000cb7d991.png)
.

**Comment by VitalyMCT** [comment]
@bechynsky This issue is with the Skillable environment's pull of instructions rather than with this GitHub repo itself. As I am also teaching this course with Skillable (this week) I asked them to resolve it and they very quickly did. It's tracked under ticket 524679 there.

**Comment by olaekdahl** [comment]
@VitalyMCT How is it teaching the course with outstanding issues not fixed yet? I've been continuing to use the DA-100 labs with the PL-300 content for now.

**Comment by VitalyMCT** [comment]
@olaekdahl It's less than ideal, that's for sure. I have to carefully navigate around the various issues in the classroom to provide students with a great learning experience. It would be much easier if the issues in this repo were just fixed promptly when MCTs file them. Current resolution time frames on this repo average from weeks to months.

**Comment by olaekdahl** [comment]
@VitalyMCT That's what I thought, thanks for letting me know. I will continue to use the DA-100 labs for now.

**Comment by bpmoring** [comment]
This issue should be resolved. I have had the lab updated to the latest GitHub repo.
