### ISSUE TITLE
Repository Structure of Github does not match the lab instructions

### ISSUE THREAD

**Issue by desertislesql** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#41]
# Module: ALL
####### Description of issue
The file structure in the installation github repo puts the files in this structure 
D:\PL300\Labs\01\Starter\ (then all the lab folders are here)

The instructions tell students to go to 
D:\PL300\Labs\ (then all the lab folders are here)

Please fix the github repo to match the instructions by removing the reference to 01\Starter

**Comment by bpmoring** [comment]
This issue should be resolved. I have had the lab update to the latest GitHub repo.
