### ISSUE TITLE
Lab 5 > Task 2 > Step 7

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#42]
1. Format pane image is different, current instructions use outdated formatting image.
2. In Task 3 the file path should be lab directory 05 rather than 06

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by bpmoring** [comment]
These issues have been addressed.
