### ISSUE TITLE
Lab 4 (Create DAX Calculations in Power BI Desktop, Part 1) > Exercise 1, Task 2

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#43]
In this task you will create the Salesperson table (direct relationship to Sales). However, the Salesperson (Performance) table does not exist because the instructions for renaming it in Lab2 are no longer there

**Comment by jamarx2** [comment]
Repeat of  issues #20 and #21.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
These steps were added into Lab 3.
