### ISSUE TITLE
Privacy Levels Step Missing

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#44]
# Module: 07
#### Step: 14 If prompted to apply changes, click Apply

After clicking 'Apply', a window pops up asking the user to specify 'Privacy Levels'. If the user checks the "Ignore Privacy Levels checks for this file" checkbox and clicks 'Save', PowerBI crashes. Changing both rows to 'Organizational' allows the user to continue. 

![image](https://user-images.githubusercontent.com/48496971/166557227-7d83ed19-814b-4b6b-b471-524b6f375d55.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
This step is in lab 2.
