### ISSUE TITLE
Lab 4 - DAX - Missing the instructions to create additional measures that will be later required in lab 6

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#45]
# Module: 05
#### Step: all

Description of issue
Exercise 2: Create Measures > Task 2: Create additional measures has been removed from PL-300 lab (https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/05-create-dax-calculations-in-power-bi-desktop.md#task-2-create-additional-measures). However, there is a dependency on the measures created in this task in the Report Lab > Exercise 1: Create a Report > Task 6: Design page 3 > Step 7 (https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/06-design-report-in-power-bi-desktop.md#task-6-design-page-3)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
These have been added back into the lab.
