### ISSUE TITLE
UI Changes in PBI Desktop makes Lab 7 Ex 2 Task 2 Step 12 incorrect

### ISSUE THREAD

**Issue by richbrooks** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#46]
# Module: 7 Create Report in Power BI Desktop Part 2
#### Step: 12
Teaching a PL-300 and one of the Students: Manny Stupariu found a UI mismatch.  Recommend instructions to be updated.
UI changes have made the following instructions on Step 12.

"Configure the format options for the visual, and in the Grid section, set the Text Size property to 20pt."

Should be something like
"Configure the format options for the visual, and in the Grid section, in the Options group, set the Global Font Size to 20pt"

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #66.

**Comment by bpmoring** [comment]
This has been addressed with the latest lab update.
