### ISSUE TITLE
Lab 4> Excercise 2: Create Measures > Task 1> Step 11

### ISSUE THREAD

**Issue by leilaczek** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#47]
# Module: 4. Create DAX Calculations in Power BI Desktop, Part 1
#### Step: 11

11. For the multi-selection of measures, configure the following requirements:

Set the format to two decimal places- even if I multi-selected  Avg Price, Max Price, Median Price, and Min Price.
and set the decimal places to 2.

It was not captured on the report view 
As a workaround, I had to do all changes manually (one by one).

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
