### ISSUE TITLE
Lab 6 > Excercise 1> Task 6> Step 8: Format the visual

### ISSUE THREAD

**Issue by leilaczek** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#48]
# Module: 6. Design a Report in Power BI Desktop, Part 1
#### Step: 08

Format the visual

Not changing the text size in the **Category Labels** but in **Callout Values**.
By doing this we will have the same effect as on the picture.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #62.

**Comment by bpmoring** [comment]
This issue has been addressed with the latest update.
