### ISSUE TITLE
Lab 7> Excercise 3: Add Conditional Formatting > Task 1> Step 10

### ISSUE THREAD

**Issue by leilaczek** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#49]
# Module: 7. Design a Report in Power BI Desktop, Part 2
#### Step: 10

ormat Style

IS
In the Background Color – Color window, in the **Format By** dropdown list, select **Field Value**.

Should be: 
In the Background Color – Color window, in the **Format Style** dropdown list, select **Field Value**.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #67.

**Comment by bpmoring** [comment]
This has been resolved with the latest update.
