### ISSUE TITLE
Path to Labfiles is not correct

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#5]
Cloning this repo or downloading as a zip results in a file system structure like: "D:\PL-300-Microsoft-Power-BI-Data-Analyst-Main\Allfiles\Labs\01\Starter\01-prepare-data-with-power-query-in-power-bi-desktop"

The extraneous "\01\Starter" should be removed.

**Comment by TesterTesterson1004** [comment]
I concur - this seems like the best solution to modify the existing /Allfiles such that:  The extraneous "\01\Starter" should be removed.

**Comment by bpmoring** [comment]
Thank you for this comment. We will look into this.

**Comment by bpmoring** [comment]
This issue has been addressed with the latest commit.
