### ISSUE TITLE
Lab 5- DAX formulas Snippets file path is wrong

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#51]
# Module: 05
#### Step: 1

Description of issue:
For your convenience, all DAX definitions in this lab can be copied from the D:\PL300\Labs\06-create-dax-calculations-in-power-bi-desktop-advanced\Assets\Snippets.txt file.
![image](https://user-images.githubusercontent.com/46898093/170122059-70c165c3-3ea3-4911-8ab5-f437cf7a1b27.png)

Correct path is: 
D:\PL300\Labs\05-create-dax-calculations-in-power-bi-desktop-advanced\Assets\Snippets.txt file.

**Comment by bpmoring** [comment]
This is updated in the latest lab instructions.
