### ISSUE TITLE
Lab 4- DAX formulas Snippets file path is wrong

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#52]
# Module: 05
#### Step: 2

Description of issue:
For your convenience, all DAX definitions in this lab can be copied from the snippets file, located in D:\PL300\Labs\05-create-dax-calculations-in-power-bi-desktop\Assets\Snippets.txt.
![image](https://user-images.githubusercontent.com/46898093/170122878-7fe5767a-fa05-4c39-bcfb-196821ccf947.png)

Correct path is: 
D:\PL300\Labs\4-create-dax-calculations-in-power-bi-desktop-advanced\Assets\Snippets.txt file.

**Comment by bpmoring** [comment]
This is updated in the latest lab version.
