### ISSUE TITLE
Typo in directory name

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#6]
Typo in directory name: "D:\PL-300-Microsoft-Power-BI-Data-Analyst-Main\Allfiles\Labs\01\Starter\09erform-data-analysis-in-power-bi-desktop". 

Should be "09-perform-data-analysis-in-power-bi-desktop".

**Comment by bpmoring** [comment]
Thank you. We will update this on Friday.

**Comment by bpmoring** [comment]
Update has been made.
