### ISSUE TITLE
Users requiring Power BI Admin

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#8]
#### Step: 00

Description of issue
The delegates need to be added to a single tenant with Power BI Admin rights to perform the task 2.  If they are all admin only one can change the setting to enabled.  All the others will see it as Enabled.  

![image](https://user-images.githubusercontent.com/36226388/157306959-455e89b6-267d-4a5c-b38d-7a16737423c8.png)

As the aim is to be focussed on the Business User they will not do this.   Yes if the delegates are on their own tenant it could work.

Personally I think this is such a risk to the course collapsing as a delegate could remove all other users including the instructor.

Fitz

**Comment by bpmoring** [comment]
We will look into this issue. Thanks.
