### ISSUE TITLE
Lab 6 - broken steps

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#85]
# Module: 00
#### Step: 22

Description of issue

Repro steps:
From the Fields pane, drag the **Sales | Profit Margin** field into the Line y-axis well/area.

You cannot drag **Profit Margin** as this measure was not created in any lab. 

Same problem in:

#### Step: 8 Add the following five Sales table fields to the Values well/area:

Orders (from the Counts folder)
Sales
Cost
**Profit
Profit Margin**

Again **Profit** and **Profit Margin** does not exist.

All of these measures were created in **DA-100 | LAB 3 | Exercise 4: Create Quick Measures** : https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/03-configure-data-model-in-power-bi-desktop.md
And in DA-100 was no logic in creating the quick measures there, because the measures were introduced later in the next module.

So, either add proper exercise steps in PL-300 LAB 4 - Exercise 2: Create Measures, before task "Create simple measures", either delete the steps from LAB 6 that use these measures.

**Comment by bpmoring** [comment]
These steps have been added to the updated labs.

**Comment by luconsta** [comment]
Hi @bpmoring ,
Could you please tell me in which lab were added these two measures? Because I have searched in the current labs from 3 to 5 and there is no mention to **Profit** and **Profit Margin** measures, but still in lab 6 & 7 we have to use them.

**Comment by luconsta** [comment]
Hi @bpmoring ,
I saw that LAB3 was updated after my last comment, and I could confirm that now I can see the "Exercise 4: Create Quick Measures".

I still don't understand why putting this exercise in **LAB3 - Model Data in Power BI Desktop** when in the related lesson there is no mention to calculations, and a more suitable place it would be **LAB4 - Create DAX Calculations in Power BI Desktop**.
