### ISSUE TITLE
Name of Directory

### ISSUE THREAD

**Issue by AroraMunish** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#9]
# Module: 00
#### Step: 00

Description of issue
Name of folder should be  "\Allfiles\Labs\", instead of Typo in directory name: "Allfiles\Labs\01\Starter"

**Comment by bpmoring** [comment]
We will look into this. Thanks.

**Comment by bpmoring** [comment]
This is the same as issue #5 closing this one.
