### ISSUE TITLE
Lab Story in lab introductions

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#90]
The Lab Story section includes the following sentence:

> However, if you intend to work through multiple labs, for the first 10 labs, we suggest you do them in the following order:

This seems to be a leftover from DA-100 or an old version of PL-300. The current PL-300 has 10 labs in total, so students who read this comment are led to believe there may be more than 10 labs. Recommend rewording this sentence for accuracy, for example simply:

> However, if you intend to work through multiple labs, we suggest you do them in the following order:

**Comment by bpmoring** [comment]
Agreed, update has been made to instructions of all labs.
