### ISSUE TITLE
SalesTerritoy dimension table no longer has 0 primary key

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#92]
# Module: 00
## Lab/Demo: 02
Exercise: 01
#### Step: 03

Description of issue
Demo data set no longer has 0 primary key but now has 1 through 11 as primarykeys
Repro steps:

1.
1.
1.

**Comment by AngieRudduck** [comment]
Confirmed. Instructions, including screenshot, will be updated over the next few weeks.

**Comment by AngieRudduck** [comment]
Will go live in November 2022 updates.
