### ISSUE TITLE
Lab 2 - Markdown issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#95]
The following segment is rather confusing, because the initial bullet point does not have the formula. Perhaps merge into one bullet point and/or resequence?

![image](https://user-images.githubusercontent.com/1765732/179856495-9b6bd089-e68a-41bb-bf5e-5f318764ce91.png)

**Comment by bpmoring** [comment]
Agreed, will include in the next update.

**Comment by AngieRudduck** [comment]
Fix included in the November 2022 updates.
