### ISSUE TITLE
Power BI Desktop updated, X-axis and Column y-axis have been renamed (instructions need to be updated)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#96]
# Module: Designing Reports
#### Step: 21

Description of issue: Screenshot is not correct anymore, as the X-axis and Column-Y axis have been renamed in latest version of Power BI Desktop

![image](https://user-images.githubusercontent.com/53346841/179979750-483d0664-8783-48b2-98d3-8bcfb175f9a2.png)

**Comment by VitalyMCT** [comment]
Is this the same as https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/issues/91? 

Which ALH is your session running on and what's the version of PBI Desktop there?

**Comment by weslbo** [comment]
Is indeed same as #91. Was using skillable this week and noticed Power BI Desktop is on Feb 22 release.

**Comment by VitalyMCT** [comment]
@bpmoring  Can this please be rectified? The students just brought it up to me again today and I had to explain it to them. We need to align the instructions with the naming on the ALH-deployed release of PBI Desktop, which is now July 2022.

**Comment by AngieRudduck** [comment]
@VitalyMCT I am in the process of making new screenshot updates over the next few weeks. Thanks.

**Comment by AngieRudduck** [comment]
This is going live in November 2022 updates.

**Comment by VitalyMCT** [comment]
@AngieRudduck I see mentions of "November 2022 updates" in multiple tickets here. Can you please help MCTs understand what they will be? Instructions? VM images? Both?

**Comment by AngieRudduck** [comment]
@VitalyMCT All issues will be released in a single update this month. As each issue is different, the fix will vary. Where the issue is for instructions, the instructions will be updated. None of the issues were specific to the VM images so those are not changing currently.

**Comment by VitalyMCT** [comment]
@AngieRudduck Understood, thank you. Would there be a ticket with release notes (or any other communication mechanism) that would advise us of the main changes in this version?
