### ISSUE TITLE
Design a Report in Power BI Desktop Lab - Enabling Maps

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#97]
The map and filled map visuals need to be enabled in Power BI Desktop as well as in Power BI Service.

The instructions should be amended to include the former.

![image](https://user-images.githubusercontent.com/1765732/180245407-2430fca7-e6ef-4d55-a497-84f590b16f74.png)

**Comment by bpmoring** [comment]
Thank you. We will include this in the next update.

**Comment by AngieRudduck** [comment]
This is going live in November 2022 updates.
