### ISSUE TITLE
Dashboard lab - out of date screenshot

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#98]
The card visualization's value should be $33M instead of $37M, to match step 17 in the instructions.

![image](https://user-images.githubusercontent.com/1765732/180281667-267d97cc-6f28-4e15-a6d3-38e28275e636.png)

**Comment by bpmoring** [comment]
Thank you. We will include this in the next update.

**Comment by AngieRudduck** [comment]
This is going live in November 2022 updates.
