### ISSUE TITLE
Design a Report in Power BI Desktop, Part 1 - Map visibility after publishing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#99]
There is a Power BI Service glitch in that maps are not visible after publishing, even though the right settings are enabled (from a while back). The workaround is to simply refresh the browser page. Can this workaround please be added as part of the lab steps?

**Comment by AngieRudduck** [comment]
The existing instructions direct users to refresh the browser to see the report at the start of the task:

![image](https://user-images.githubusercontent.com/34583336/200869983-84a3d0b3-39da-493e-bab3-535d9ad54f9b.png)

However, I've added additional instructions at the map visual to go live in November 2022 updates:

![image](https://user-images.githubusercontent.com/34583336/200870132-69b94207-4799-4211-8eff-4206c10a5baa.png)

**Comment by VitalyMCT** [comment]
@AngieRudduck The existing instructions in the step you included in the 1st screenshot do not address the issue. They tell attendees to refresh the contents of the workspace if they do not see the items there. The issue is not around visibility of report and dataset within the workspace. Rather, it's around the display of the map visual when the report itself is opened.

Also, to clarify my original note, rather than the map being invisible users currently get an error message. The error message says the map visualization is disabled in the tenant settings (or something to that effect). Can the update be closely aligned to address the issue the attendees are having?

**Comment by AngieRudduck** [comment]
@VitalyMCT I have added more explicit verbiage per your request.

![image](https://user-images.githubusercontent.com/34583336/201385405-d19457e9-c804-42a5-b0d1-6cef5acf4d91.png)

**Comment by VitalyMCT** [comment]
@AngieRudduck That looks perfect and will really help future course attendees, thank you!
